Repository Automattic/pocket-casts-android, pull requests merged in 2023-11, with the labels that each got.

#1503 Playback 2023: Entry point
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/EndOfYearLaunchBottomSheet.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/EndOfYearPromptCard.kt
  modules/features/endofyear/src/main/res/drawable/eoy_review.xml
  modules/features/endofyear/src/main/res/drawable/img_2022.xml
  modules/features/endofyear/src/main/res/drawable/img_2022_big.xml
  modules/features/endofyear/src/main/res/drawable/img_2023_modal.xml
  modules/features/endofyear/src/main/res/drawable/img_23.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/BottomSheetContent.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
Labels: Playback 2023

#1502 Playback 2023 - Year over year listening time story
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  app/src/test/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModelTest.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ShareableTextProvider.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/CategoryPillar.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/GradientPillar.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/EndOfYearLaunchBottomSheet.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/EndOfYearPromptCard.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryYearOverYearView.kt
  modules/features/endofyear/src/main/res/drawable/eoy_review.xml
  modules/features/endofyear/src/main/res/drawable/img_2022.xml
  modules/features/endofyear/src/main/res/drawable/img_2022_big.xml
  modules/features/endofyear/src/main/res/drawable/img_2023_modal.xml
  modules/features/endofyear/src/main/res/drawable/img_23.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/BottomSheetContent.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/YearOverYearListeningTime.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/StoryYearOverYear.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
Labels: Playback 2023

#1391 Dangermattic Setup
  .buildkite/commands/danger-pr-check.sh
  .buildkite/pipeline.yml
  .rubocop.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: Tooling

#1506 Playback 2023: Completion rate story
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/CompletionRateCircle.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/EpisodesStartedAndCompleted.kt
  modules/services/repositories/build.gradle
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/StoryCompletionRate.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImplTest.kt
Labels: Playback 2023

#1510 Avoid audio skip back when a streaming episode is downloaded
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: bug

#1515 Extract free trial info
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModelTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/whatsnew/WhatsNewViewModelTest.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/UpsellButtonTitle.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
Labels: Playback 2023

#1517 Playback 2023: Plus purchase flow
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/PaidStoryWallView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryButton.kt
  modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
Labels: Playback 2023

#1522 Playback 2023: Sync 2022 and 2023 listening history
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
  modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/HistoryManager.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImplTest.kt
Labels: Playback 2023

#1523 Playback 2023: Tracks
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: Playback 2023

#1524 Playback 2023 - Improvements
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ShareableTextProvider.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/PaidStoryWallView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryButton.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/SnapShot.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryEpilogueView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedCategoriesView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedNumbersView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListeningTimeView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryLongestEpisodeView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopFivePodcastsView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopPodcastView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryYearOverYearView.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/EpisodesStartedAndCompleted.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/TopPodcast.kt
Labels: Playback 2023

#1526 Enable bookmarks with Patron early access in 7.52
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: bookmarks

#1429 Fix user episodes getting removed from up next
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
Labels: upnext

#1528 Playback 2023 - Update listened time font size
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListeningTimeView.kt
Labels: Playback 2023

#1530 Unlock orientation after stories dismiss
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
Labels: End of Year

#1534 Dangermattic: fix release label typo
  Dangerfile
  Gemfile.lock
Labels: Tooling

#1531 Bookmarks + Playback: Add handling for when both the bookmarks what's new and the playback prompt will show
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
Labels: Playback 2023

#1536 Playback 2023 - animations
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/utils/Util.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedNumbersView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryLongestEpisodeView.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt
Labels: Playback 2023, unit-tests-exemption

#1537 Enable Playback 2023
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Playback 2023

#1532 Merge/release 7.51 into main
  CHANGELOG.md
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#1538 Bookmarks: fixes
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/HeadphoneAction.kt
Labels: bookmarks

#1542 Bookmarks - Fix upsell display
  base.gradle
  gradle/libs.versions.toml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
Labels: bookmarks

#1545 Playback 2023 - Update completion rate query
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
Labels: Playback 2023

#1541 Update whats new version code
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
Labels: bookmarks

#1540 Merge release/7.52-rc-1 into main
  CHANGELOG.md
  base.gradle
  gradle/libs.versions.toml
  metadata/release_notes.txt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  version.properties
Labels: releases

#1544 Bookmarks - Fix add bookmark not showing at times
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
Labels: bookmarks

#1547 Merge release/7.52-rc-2 to main
  .configure
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  version.properties
Labels: releases

#1550 Use suspend method when playing bookmarks
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
Labels: bookmarks

#1546 Bookmarks - Fix user bookmarks sync when feature is disabled
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
Labels: bookmarks

#1551 Fix occasional crash on moving player shelf item
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfTouchCallback.kt
Labels: bug

#1552 Allow bookmark incremental sync when delete is null
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
Labels: bookmarks

#1554 Playback2023 - UI design feedback
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/GradientPillar.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/PaidStoryWallView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryButton.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryText.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryEpilogueView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopFivePodcastsView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryYearOverYearView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/Story.kt
Labels: Playback 2023

#1555 Playback 2023 - Add YoY story animation
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/GradientPillar.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryYearOverYearView.kt
Labels: Playback 2023

#1557 Bookmarks - fixes
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
Labels: bookmarks

#1558 Catch exception if Stories call to load history fails
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
Labels: End of Year

#1559 Merge release 7.52-rc-3 into main
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/GradientPillar.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/PaidStoryWallView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryButton.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryText.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryEpilogueView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopFivePodcastsView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryYearOverYearView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfTouchCallback.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/Story.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
  version.properties
Labels: releases

#1560 Fix podcast screen edit bookmark action
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
Labels: bookmarks

#1561 Fetch latest episode url before playing episode
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt
Labels: bug

#1562 Handle an illegal state exception
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
Labels: bug

#1563 Merge release 7.52-rc-4 into main
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  version.properties
Labels: releases

#1564 Merge release 7.52 into main
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#1392 Rubocop fixes and configuration update
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile.lock
  fastlane/Fastfile
  scripts/generate_themes_image.rb
  scripts/themes/Gemfile
  scripts/themes/Gemfile.lock
  scripts/themes/download_themes.rb
  scripts/themes/generate_kotlin.rb
  scripts/themes/generate_kotlin_compose.rb
  scripts/themes/generate_xml.rb
Labels: Tooling

#1548 Fix file deletion when the episode is marked as played
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
Labels: user episodes

#1571 Move help menu to profile screen
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/settings/src/main/AndroidManifest.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpActivity.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt
  modules/features/settings/src/main/res/drawable/settings_help.xml
  modules/services/images/src/main/res/drawable/ic_help.xml
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsScreen.kt
Labels: enhancement

#1573 Use type converter that cannot return null for date to avoid crash
  CHANGELOG.md
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/DateTypeConverter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/SafeDateTypeConverterTest.kt
Labels: bug

#1567 Merge release/7.53-rc-1 into main
  CHANGELOG.md
  metadata/release_notes.txt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/DateTypeConverter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/SafeDateTypeConverterTest.kt
  version.properties
Labels: releases

#1574 Change bookmarks tab order
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
Labels: bookmarks

#1496 Adds LoggingInScreenViewModel Unit tests
  wear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/LoggingInScreenViewModelTest.kt
Labels: unit tests
