Repository Automattic/pocket-casts-android, pull requests merged in 2023-08, with the labels that each got.

#1224 Bookmarks - Add parent container on episode page
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/res/layout-land/fragment_episode.xml
  modules/features/podcasts/src/main/res/layout/fragment_episode.xml
  modules/features/podcasts/src/main/res/layout/fragment_episode_container.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: bookmarks

#1231 Bookmarks - Add to episode details page
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksSortByDialog.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/HeaderRow.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/MessageView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoBookmarksView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/PlusUpsellView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt
  modules/features/podcasts/src/main/res/layout/fragment_episode_container.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkItem.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/TimePlayButton.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/loading/LoadingView.kt
Labels: bookmarks

#1236 Bookmarks - Show bookmark icon on podcast page episode rows
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/podcasts/src/main/res/layout/adapter_episode.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
Labels: bookmarks

#1238 Merge/release 7.44 to main
  Gemfile
  Gemfile.lock
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#1233 fix #1226 keyboard reopening bug fixed
  modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
Labels: first time contribution

#1234 Settings Sync - Refactor archive settings to be UserSettings
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoArchiveAfterPlayingSetting.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoArchiveInactiveSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
Labels: sync settings

#1232 Fix Notification permissions warning
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/repositories/src/main/AndroidManifest.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/NotificationPermissionChecker.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: first time contribution

#1230 Settings sync - Refactor appearance settings to be `UserSetting`s
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AppIconSetting.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoArchiveAfterPlayingSetting.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoArchiveInactiveSetting.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ThemeSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/EpisodeFileMetadata.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/AppIcon.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt
Labels: sync settings

#1240 Make auto add to up next settings a `UserSetting`
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoAddSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoAddSettingsViewModel.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoAddUpNextLimitBehaviour.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
Labels: sync settings

#1239 Bookmarks - Display for user episodes
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/res/layout/fragment_bookmarks_container.xml
  modules/features/profile/build.gradle
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheet.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
  modules/features/profile/src/main/res/layout/bottom_sheet_cloud_file.xml
  modules/services/images/src/main/res/drawable/ic_chevron.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/component/FileStatusIconsView.kt
  modules/services/views/src/main/res/layout/view_file_status_icons.xml
Labels: bookmarks

#1245 Merge release/7.45-rc-1
  CHANGELOG.md
  app/proguard-rules.pro
  automotive/build.gradle
  metadata/release_notes.txt
  version.properties
  wear/build.gradle
Labels: releases

#1249 Settings Sync - Make file settings into UserSettings
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
Labels: sync settings

#1253 Bookmarks - Link edit action
  modules/features/player/src/main/AndroidManifest.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectHelper.kt
Labels: bookmarks

#1261 Merge release/7.45-rc-2 into main
  modules/services/images/src/main/res/drawable-xhdpi/ic_edit.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarkAction.kt
  version.properties
Labels: releases

#1267 Bookmarks - Add bookmark from headset hook
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/services/images/src/main/res/drawable/ic_notification_edit.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelperImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/res/raw/tone.mp3
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Context.kt
Labels: bookmarks

#1274 Bookmark - Link Upsell flow
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
  modules/features/player/build.gradle
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfItem.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/MessageView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoBookmarksView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/PlusUpsellView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/NoBookmarkViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheet.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/RequirePlusScreen.kt
Labels: bookmarks

#1284 Bookmarks - Update headphone controls options display
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Labels: bookmarks

#1289 Merge/release 7.45 into main
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#1294 Merge/release 7.45 to main
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  version.properties
Labels: releases

#1302 Fix Protocol Buffers in the release build
  app/proguard-rules.pro
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: bookmarks

#1276 Bookmark icon on Delete fix
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeListAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/UserEpisodeViewHolder.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheet.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/component/FileStatusIconsView.kt
Labels: bookmarks

#1317 Merge release 7.46 -rc-3 into main
  CHANGELOG.md
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastAndEpisodeDetailsCoordinator.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  version.properties
Labels: releases

#1319 Bookmarks - Update Add Bookmark Headphone Control
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
Labels: bookmarks

#1311 Bookmarks misc - part 1
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/BookmarkDaoTest.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoBookmarksView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt
  modules/features/podcasts/src/main/res/layout/adapter_no_results.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt
  modules/services/images/src/main/res/drawable/logo_pocket_casts.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
Labels: bookmarks
