Repository Automattic/pocket-casts-android, pull requests merged in 2024-01, with the labels that each got.

#1643 Fix wear update effects UI not updating
  CHANGELOG.md
  app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffectsDataTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffects.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffectsData.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsScreen.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt
Labels: bug, wear os

#1625 Remove unused getPodcastEpisodesListOrderBy method
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
Labels: tech debt

#1638 Improve wear handling of user files
  CHANGELOG.md
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserEpisodeImage.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/DeleteState.kt
  wear/build.gradle.kts
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
Labels: bug, wear os

#1629 Using compose-bom
  base.gradle
  gradle/libs.versions.toml
Labels: tech debt

#1623 Remove GlobalScope usage in MediaSessionManager
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: tech debt

#1662 Set label for close button in up next screen
  CHANGELOG.md
  modules/features/player/src/main/res/layout/fragment_upnext.xml
Labels: upnext

#1656 Merge release/7.54-rc-5 into main
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
  modules/features/settings/src/main/res/layout/fragment_settings_appearance.xml
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/images/src/main/res/color/color_primary_container_40.xml
  modules/services/images/src/main/res/drawable/widget_background.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt
  modules/services/repositories/src/main/res/layout/widget.xml
  modules/services/repositories/src/main/res/layout/widget_default_theme.xml
  modules/services/repositories/src/main/res/layout/widget_dynamic_colors_theme.xml
  modules/services/repositories/src/main/res/values-v31/styles.xml
  modules/services/repositories/src/main/res/values/styles.xml
  modules/services/repositories/src/main/res/xml/widget.xml
  version.properties
Labels: releases

#1665 Fix large bitmap crash
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
Labels: bug

#1666 Fix Incorrect playback speed shown on the media notification
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt
  modules/features/taskerplugin/build.gradle.kts
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Double.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/DoubleTest.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt
Labels: bug

#1671 Delete EpisodeManagerTest
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerTest.java
Labels: tech debt

#1670 Merge/release 7.54 into main
  CHANGELOG.md
  app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffectsDataTest.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffects.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffectsData.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  version.properties
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsScreen.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt
Labels: releases

#1678 Merge release/7.55-rc-1 into main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#1677 Player: Episode artwork - add image ratio constraint
  modules/features/player/src/main/res/layout/adapter_player_header.xml
Labels: bug

#1668 Migrate FileStorage from Java to Kotlin
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
  modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModelTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FileStorage.java
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FileStorage.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java
Labels: tech debt

#1667 Move Danger to GitHub Actions
  .buildkite/commands/danger-pr-check.sh
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
Labels: Tooling

#1683 Remove Gradle Wrapper Validation GitHub workflow
  .github/workflows/gradle-wrapper-validation.yml
Labels: Tooling

#1674 Remove In app review feature flag
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelperTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModel.kt
  modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModelTest.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelper.kt
Labels: tech debt

#1681 Remove ADD_PATRON_ENABLED feature flag
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
  modules/features/account/src/main/res/drawable-hdpi/upgrade_background_glows.png
  modules/features/account/src/main/res/drawable-mdpi/upgrade_background_glows.png
  modules/features/account/src/main/res/drawable-xhdpi/upgrade_background_glows.png
  modules/features/account/src/main/res/drawable-xxhdpi/upgrade_background_glows.png
  modules/features/account/src/main/res/drawable-xxxhdpi/upgrade_background_glows.png
  modules/features/account/src/main/res/drawable/plus_bw.xml
  modules/features/account/src/main/res/drawable/pocket_casts_white.xml
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlusSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
  modules/features/settings/src/main/res/drawable-xhdpi/ic_plus_tile.png
  modules/features/settings/src/main/res/drawable/ic_cloud_storage_old.xml
  modules/features/settings/src/main/res/drawable/ic_desktop_apps_old.xml
  modules/features/settings/src/main/res/drawable/plus_folder.xml
  modules/features/settings/src/main/res/layout/fragment_plus_settings.xml
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/images/src/main/res/drawable/cloud_storage.xml
  modules/services/images/src/main/res/drawable/desktop_apps.xml
  modules/services/images/src/main/res/drawable/folder.xml
  modules/services/images/src/main/res/drawable/themes_icons.xml
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SignInState.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: tech debt

#1685 Merge release 7.55-rc-2 into main
  Gemfile.lock
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  version.properties
Labels: releases

#1689 Revert "Remove Gradle Wrapper Validation GitHub workflow"
  .github/workflows/gradle-wrapper-validation.yml
Labels: Tooling

#1684 Android14 - Specify foreground service types
  app/src/main/AndroidManifest.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt
Labels: Android 14

#1686 Android 14 - Upgrade cast lib
  gradle/libs.versions.toml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
Labels: Android 14

#1687 Add tests for FileUtil
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/FileUtilTest.kt
Labels: tech debt

#1692 Adjust GitHub workflow reference to use Dangermattic's main branch
  .github/workflows/run-danger.yml
Labels: Tooling

#1696 Fix native share url handling
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
Labels: bug

#1691 Migrate FileUtil from Java to Kotlin
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FileStorage.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtilWrapper.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/StringUtil.java
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/FileUtilTest.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/OpmlExporter.kt
Labels: tech debt

#1695 Update Bookmarks Plus benefits
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: polish

#1693 Add remaining named settings that currently sync to new named settings sync call
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1702 Bookmarks benefits strings updates
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: polish

#1701 Remove BOOKMARKS_ENABLED feature flag
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/settings/advanced/AdvancedSettingsTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  app/src/test/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModelTest.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfItem.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModelTest.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/EpisodeListBookmarkViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheetFragment.kt
  modules/features/profile/src/main/res/layout/bottom_sheet_cloud_file.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/whatsnew/WhatsNewViewModelTest.kt
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/HeadphoneAction.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/earlyaccess/EarlyAccessHelper.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/earlyaccess/EarlyAccessStrings.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/BookmarkFeatureControl.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/FeatureWrapper.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/earlyaccess/EarlyAccessHelperTest.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/earlyaccess/EarlyAccessStringsTest.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/BookmarkFeatureControlTest.kt
Labels: tech debt

#1703 Add new sync call and sync currently-syncing podcast settings with it
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodePlayingStatus.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/BoolSetting.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/BoolSettingKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/BoolSettingOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/DoubleSetting.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/DoubleSettingKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/DoubleSettingOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/Int32Setting.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/Int32SettingKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/Int32SettingOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/PodcastSettings.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/PodcastSettingsKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/PodcastSettingsOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/Record.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/RecordKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/RecordOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUpdateRequest.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUpdateRequestKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUpdateRequestOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUpdateResponse.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUpdateResponseKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUpdateResponseOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserBookmark.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserBookmarkKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserBookmarkOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserDevice.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserDeviceKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserDeviceOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserEpisode.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserEpisodeKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserEpisodeOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserFolder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserFolderKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserFolderOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserPlaylist.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserPlaylistKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserPlaylistOrBuilder.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserPodcast.java
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserPodcastKt.kt
  modules/services/protobuf/src/main/java/com/pocketcasts/service/api/SyncUserPodcastOrBuilder.java
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
Labels: sync settings, unit-tests-exemption

#1705 Update tracking source
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
Labels: analytics

#1697 Remove custom bottom sheet behavior
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/helper/NestedCoordinatorLayout.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/helper/PCBottomSheetBehavior.java
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/player/src/main/res/layout-land/adapter_player_header.xml
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/features/player/src/main/res/layout/fragment_player_container.xml
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
Labels: bug, tech debt, enhancement

#1710 ci: submit Gradle dependencies to GH dependency graph
  .github/workflows/submit-gradle-dependencies.yml
Labels: Tooling

#1708 Adding incremental sync of episodes with the new endpoint
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodePlayingStatus.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodePlayingStatusTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
Labels: sync settings

#1712 Submit `wear` and `automotive` dependencies to GitHub as well
  .github/workflows/submit-gradle-dependencies.yml
Labels: Tooling

#1699 Remove default value for `needsSync` when updating a setting
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsOptionsDialog.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaNotificationControlsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoAddSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTracker.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NewEpisodeNotificationAction.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/AppIcon.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsViewModel.kt
Labels: sync settings

#1700 Sync settings on the "Auto archive" screen
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1723 Add report violation option
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfItem.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/res/layout/fragment_podcast.xml
  modules/features/podcasts/src/main/res/menu/podcast_menu.xml
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/images/src/main/res/drawable/ic_flag.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/extensions/Fragment.kt
  modules/services/ui/src/main/res/values/themes.xml
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt
Labels: enhancement

#1727 Merge release 7.56 into main
  CHANGELOG.md
  Gemfile.lock
  metadata/release_notes.txt
  version.properties
Labels: releases

#1726 Plus promotion login
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/account/build.gradle.kts
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivityContract.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModel.kt
  modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingExitInfo.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
Labels: enhancement

#1732 Merge release 7.56-rc-2 into main
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
  version.properties
Labels: releases

#1735 Fix starring episode from full-screen player does not prevent episode from being archived
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
Labels: bug

#1738 Sync grid layout setting
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsOptionsDialog.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/PodcastGridLayoutType.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1640 Warn when changing to metered network if setting is enabled
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
  modules/features/shared/build.gradle.kts
  modules/features/shared/src/main/AndroidManifest.xml
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcherImpl.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/di/SharedModule.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/NetworkConnectionWatcher.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManagerNetworkWatcher.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/NotificationBroadcastReceiver.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManagerNetworkWatcherTest.kt
  modules/services/utils/src/main/AndroidManifest.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/WarningsHelper.kt
Labels: bug

#1742 Fix artwork aspect ratio
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt
Labels: bug, unit-tests-exemption

#1743 Cherry pick #1726 and #1742
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/account/build.gradle.kts
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivityContract.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModel.kt
  modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingExitInfo.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt
Labels: unit-tests-exemption

#1747 Merge release 7.56-rc-3 into main
  version.properties
Labels: releases

#1744 Allow Danger to run on forked repos using GITHUB_TOKEN
  .github/workflows/run-danger.yml
Labels: Tooling

#1749 Fix formatting
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: bug

#1748 Sync row action setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1753 Add content type to playback events
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: analytics, unit-tests-exemption

#1736 Sync queue and effects settings for podcasts
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/81.json
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/82.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
Labels: sync settings

#1754 Android 14 - Add foreground service media playback permission
  app/src/main/AndroidManifest.xml
Labels: Android 14

#1746 Sync playback effects setting
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/TrimMode.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt
Labels: sync settings

#1755 Sync up next swipe setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1759 Sync episode grouping setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PodcastGrouping.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1758 Sync media notification actions setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaNotificationControlsFragment.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManagerNetworkWatcher.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManagerNetworkWatcherTest.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1761 Sync keep awake and open player settings
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1760 Sync show archived setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1767 Bump media3 from 1.0.0 to 1.0.2
  gradle/libs.versions.toml
Labels: tech debt

#1763 Sync intelligent playback setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1766 Sync auto play setting
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1769 Sync hide playback notification setting
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: bug, sync settings

#1765 Sync play up next item on tap setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1768 Sync play over notifications setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/PlayOverNotificationSetting.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings
