Repository Automattic/pocket-casts-android, pull requests merged in 2024-11, with the labels that each got.

#3132 Custom Playback Settings: Update distinctUntilChanged condition for selecting effects tabs
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
Labels: [Type] Other, [Project] Custom Playback Settings

#3136 Custom Playback Settings - Analytics
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Debouncer.kt
Labels: [Type] Feature, unit-tests-exemption, [Project] Custom Playback Settings

#3149 [Project] Manage Downloaded Episodes - Display Modal when running on low storage and opening Storage & Data Use screen
  app/lint-baseline.xml
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  app/src/test/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModelTest.kt
  automotive/lint-baseline.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsFragment.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/ModalBottomSheet.kt
  modules/services/images/src/main/res/drawable/swipe_affordance.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
  wear/lint-baseline.xml
Labels: [Type] Feature, [Project] Manage Downloaded Episodes

#3163 Add year property to End of Year analytics
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt
  modules/services/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt
Labels: [Type] Other, [Project] End of Year

#3153 [Project] Manage Downloaded Episodes - Snooze Low Storage Modal
  app/lint-baseline.xml
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/settings/SettingsImplTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Labels: [Type] Feature, [Project] Manage Downloaded Episodes

#3154 Fix notification color
  CHANGELOG.md
  modules/services/repositories/src/main/res/values/colors.xml
Labels: [Type] Bug, [Area] Notification

#3167 [Paywall Experiment] - Update anon uuid
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt
Labels: [Type] Bug, [Project] Paywall Experiments

#3146 Improve general settings
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Settings.kt
Labels: [Type] Enhancement, [Area] Settings

#3165 Custom Playback Effects - Update trim mode component and segmented bar
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
  modules/features/player/src/main/res/color/trim_mode_background.xml
  modules/features/player/src/main/res/color/trim_stroke_color.xml
  modules/features/player/src/main/res/layout/fragment_effects.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SegmentedTabBar.kt
  modules/services/ui/src/main/res/values/dimens.xml
  modules/services/ui/src/main/res/values/styles.xml
Labels: [Type] Other, [Project] Custom Playback Settings

#3147 Custom Playback Settings - Enable remote FF
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: [Type] Other, [Project] Custom Playback Settings

#3174 Extend story preview duration to 10 seconds
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Story.kt
Labels: [Project] End of Year, [Type] Enhancement

#3168 [Project] Manage Downloaded Episodes - Add Tracks
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
Labels: [Area] Analytics, [Type] Core, [Project] Manage Downloaded Episodes

#3151 [Project] Manage Downloaded Episodes - Display Modal when running on low storage and turn on Auto Download
  app/lint-baseline.xml
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/DeviceStorageUtil.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/LowStorageDetector.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtil.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/LowStorageDetectorTest.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtilTest.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
Labels: [Type] Feature, [Project] Manage Downloaded Episodes

#3178 Add configurable duartion formatting
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/localization/helper/DurationUtilTest.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/LongestEpisodeStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TotalTimeStory.kt
  modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/DurationUtil.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Project] End of Year, [Type] Enhancement

#3175 Improve EoY auto scrolling
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CoverStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/EndingStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/NumberOfShowsStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/RatingsStory.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingList.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt
Labels: [Project] End of Year, unit-tests-exemption, [Type] Enhancement

#3177 Update completion rate story animation
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CompletionRateStory.kt
Labels: [Project] End of Year, [Type] Enhancement

#3180 Retry streaming and downloading with different headers
  CHANGELOG.md
  modules/services/servers/build.gradle.kts
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptor.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt
  modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptorTest.kt
Labels: [Type] Enhancement, [Area] Downloads, [Area] Network

#3179 Update Year vs Year story UI
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/YearVsYearStory.kt
Labels: [Project] End of Year, unit-tests-exemption, [Type] Enhancement

#3176 Update Top 1 Show story texts
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-ca/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Project] End of Year, [Type] Enhancement

#3123 Enable EoY feature flag
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: [Type] Other, [Project] End of Year

#3182 Update EoY progress bar
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
  modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PagerProgressingIndicator.kt
Labels: [Project] End of Year, [Type] Enhancement

#3187 [Project] Manage Downloaded Episodes - Update Pencil Icon
  modules/services/images/src/main/res/drawable/pencil_cleanup.xml
Labels: [Type] Enhancement, [Project] Manage Downloaded Episodes

#3188 Update Dangermattic dependency
  Gemfile
  Gemfile.lock
Labels: [Type] Tooling, [Area] Dependencies

#3186 Use image instead of precomputed text in EoY sheet
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/EndOfYearLaunchBottomSheet.kt
  modules/services/images/src/main/res/drawable/end_of_year_2024_playback_text.xml
Labels: [Project] End of Year, [Type] Enhancement

#3189 Do not reset Top Show animation for screenshots
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt
Labels: [Project] End of Year, [Type] Enhancement

#3191 Warn about transitive dependencies
  build.gradle.kts
Labels: [Type] Tooling, [Area] Tooling

#3170 [Paywall Experiment] - Run Experiment only from onboarding and profile
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
Labels: [Type] Enhancement, [Project] Paywall Experiments

#2868 Run lint in release variant
  .buildkite/commands/lint.sh
Labels: [Type] Tooling

#3194 [Paywall Experiment] - Use the same UUID for both Tracks and Explat
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLogInViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/IdentifyingTracker.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/di/ExperimentModule.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt
  modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProviderTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
Labels: [Type] Bug, [Project] Paywall Experiments

#3190 Logging Refresh call times
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: [Type] Enhancement, [Area] Refresh Podcasts

#3166 [Auto Downloading] - Disable all podcasts auto download status when disabling the Global Auto Download
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
Labels: [Type] Bug, [Project] Auto Downloading Episodes

#3196 Keep screen alive during EoY flow
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt
Labels: [Project] End of Year, [Type] Enhancement

#3192 Update date added podcast display sort order
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ExternalDataDaoTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/utils/FakeFileGenerator.kt
  app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/PodcastFolderHelperTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/PodcastFolderHelper.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/PodcastsSortType.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
Labels: [Type] Other, [Area] Podcasts Tab

#3197 Apply correct sort order in ExternalDataDao
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ExternalDataDaoTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ExternalDataDao.kt
Labels: [Type] Bug, [Project] Nova Launcher, [Project] Engage SDK

#3198 [Project] Manage Downloaded Episodes - Enable remote feature flag
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: [Type] Core, [Project] Manage Downloaded Episodes

#3171 Don't update episode metadata on Wear OS or Automotive
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
Labels: [Type] Enhancement, [Area] Refresh Podcasts

#3203 Merge release 7.76 into main
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-ca/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  version.properties
Labels: releases

#3210 Merge/release 7.77 rc1 into main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#3216 Fix release notes formatting
  CHANGELOG.md
Labels: [Type] Other, [Area] Documentation

#3200 Remove unused data and repository code
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/BookmarkDaoTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/FolderDaoTest.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/GoogleSignInButtonViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/FolderDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastRatingsDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/TranscriptDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextChangeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UserEpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/NetworkRequirements.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/FileConverter.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/PricePair.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/StatsManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/CachedServerCallback.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/PostCallbackDefault.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServiceManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/cdn/StaticServiceManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/discover/SearchResult.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/extensions/JsonReader.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/refresh/RefreshServiceManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ResponsePodcasts.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListViewModel.kt
Labels: [Type] Tech Debt, [Area] Database

#3213 Add episode basic authentication support
  CHANGELOG.md
  modules/services/servers/build.gradle.kts
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/interceptors/BasicAuthInterceptor.kt
  modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptorTest.kt
  modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/interceptors/BasicAuthInterceptorTest.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: [Type] Enhancement, [Area] Playback

#3218 Inject OkHttpClient to episode details task and to status checker
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/ServiceStatusChecker.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/CastsWorkerFactory.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerDataSourceFactory.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServiceManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt
Labels: [Type] Tech Debt, [Area] Network

#3221 Fix dialog title
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CrashMessageDialog.kt
Labels: [Type] Bug, [Project] End of Year

#3219 Fix effects being lost when paused
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerSeekBar.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
Labels: [Type] Bug, [Area] Player UI

#3214 [Compose Migration] Migrate shelf list items to Compose - Part i
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfItemRow.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfTitleRow.kt
  modules/features/player/src/main/res/layout/adapter_shelf_item.xml
  modules/features/player/src/main/res/layout/adapter_shelf_title.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfRowItem.kt
Labels: [Type] Tech Debt, compose migration, unit-tests-exemption, [Area] Player UI

#3215 [Compose Migration] Migrate shelf list items to Compose - Part ii
  modules/features/player/build.gradle.kts
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfTouchCallback.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/MenuShelfItems.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfBottomSheetPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfItemRow.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfRearrangeActionsPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfTitleRow.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfBottomSheetViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModel.kt
  modules/features/player/src/main/res/layout/fragment_shelf.xml
  modules/features/player/src/main/res/layout/fragment_shelf_bottom_sheet.xml
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModelTest.kt
Labels: [Type] Tech Debt, compose migration, [Area] Player UI

#3220 Start Android 15 upgrade
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/PackageValidator.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt
Labels: [Type] Tech Debt, [Area] Android 15

#3222 Shelf Row Item - Update ripple configuration
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/MenuShelfItems.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfItemRow.kt
Labels: [Type] Other, [Area] Theme

#3224 Make seen EoY segments filled
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
Labels: [Type] Other, [Project] End of Year

#3227 Cherry pick #3217 and #3219 into 7.77
  CHANGELOG.md
  lint.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerSeekBar.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
Labels: [Type] Bug, [Area] Playback

#3223 Fix clip sharing memory leak
  build.gradle.kts
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/clip/ShareClipViewModel.kt
  modules/services/media-ffmpeg/src/main/kotlin/au/com/shiftyjelly/pocketcasts/media/FFmpegMediaService.kt
Labels: [Type] Bug, [Project] Reimagine Sharing

#3229 Use content extension to set up fragments
  automotive/build.gradle.kts
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveAboutFragment.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveLicensesFragment.kt
  modules/features/account/build.gradle.kts
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeDoneFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeEmailFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangePwdFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
  modules/features/podcasts/build.gradle.kts
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderChooserFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderCreateFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditPodcastsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateFragment.kt
  modules/features/profile/build.gradle.kts
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/CancelConfirmationFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/champion/PocketCastsChampionBottomSheetDialog.kt
  modules/features/reimagine/build.gradle.kts
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/ShareDialogFragment.kt
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/clip/ShareClipFragment.kt
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/episode/ShareEpisodeFragment.kt
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/podcast/SharePodcastFragment.kt
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/timestamp/ShareEpisodeTimestampFragment.kt
  modules/features/search/build.gradle.kts
  modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchResultsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/services/views/build.gradle.kts
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/OptionsDialog.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BatteryRestrictionsSettingsFragment.kt
Labels: [Type] Tech Debt, [Area] Compose

#3226 [Tooling] Automate creation of backmerge PRs
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: [Type] Tooling, [Area] Tooling

#3230 Update Tracks to 6.0.3
  gradle/libs.versions.toml
Labels: [Type] Bug, [Area] Dependencies

#3231 Fix low storage card theme colors
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt
  modules/features/podcasts/src/main/res/layout/fragment_profile_episode_list.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
Labels: [Type] Enhancement, [Project] Manage Downloaded Episodes

#3236 Remove ExoOkHttp feature flag
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerDataSourceFactory.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: [Type] Other, [Area] Network

#3237 Merge/release 7.77 rc 2 into main
  CHANGELOG.md
  gradle/libs.versions.toml
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CrashMessageDialog.kt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt
  modules/features/podcasts/src/main/res/layout/fragment_profile_episode_list.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
  version.properties
Labels: releases

#3233 Add UserAvatar composable
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserAvatar.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/preview/ThemePreviewParameterProvider.kt
  modules/services/images/src/main/res/drawable/ic_account_free.xml
  modules/services/images/src/main/res/drawable/ic_account_plus.xml
Labels: [Type] Tech Debt, [Area] Compose

#3234 Support edge-to-edge on the podcasts list page
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/view/LockableBottomSheetBehavior.kt
  app/src/main/res/layout/activity_main.xml
  dependencies.gradle.kts
  gradle/libs.versions.toml
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/StatusBarSpacer.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoActivity.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
  modules/features/profile/src/main/res/layout-land/fragment_profile.xml
  modules/features/profile/src/main/res/layout/fragment_profile.xml
  modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt
  modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/ShareDialogFragment.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/ThemedTopAppBar.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt
  modules/services/ui/src/main/res/values/themes.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Toolbar.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/View.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseAppCompatDialogFragment.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragment.kt
Labels: [Type] Tech Debt, [Area] Android 15

#3238 Refactor shelf items logic
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerClickListener.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfBottomSheetPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfRearrangeActionsPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModelTest.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModelTest.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModelTest.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
Labels: [Type] Tech Debt, [Area] Player UI

#3212 Feature/add to up next after sync
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
Labels: [Type] Enhancement, [Area] Sync

#3250 Update referral share message
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Type] Other, [Project] Referrals

#3248 Suffix filter DAO methods that aren't Coroutines with 'blocking' to make upgrading easier
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/ui/PlaybackServiceTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  automotive/src/androidTest/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackServiceTest.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterViewModel.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/DurationOptionsFragment.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/EpisodeOptionsFragment.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/PodcastOptionsFragment.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/TimeOptionsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadFiltersFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/playplaylist/ActionRunnerPlayPlaylist.kt
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/queryfilterepisodes/ActionRunnerQueryFilterEpisodes.kt
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/queryfilters/ActionRunnerQueryFilters.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/FilterSelectFragment.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/filter/FilterViewModel.kt
Labels: [Type] Tech Debt, [Area] Database

#3247 Replace refresh section with Compose UI
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/RefreshSection.kt
  modules/features/profile/src/main/res/drawable/ic_retry_small_spinnable.xml
  modules/features/profile/src/main/res/layout-land/fragment_profile.xml
  modules/features/profile/src/main/res/layout/fragment_profile.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/RefreshState.kt
Labels: [Type] Tech Debt, [Area] Profile Tab, [Area] Compose

#3251 Update profile header UI
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileHeader.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileStats.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
Labels: [Type] Other, [Area] Profile Tab

#3252 Migrate Plus upgrade in profile tab to Compose UI
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileUpgradeSection.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt
  modules/features/profile/src/main/res/layout-land/fragment_profile.xml
  modules/features/profile/src/main/res/layout/fragment_profile.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Labels: [Type] Tech Debt, [Area] Profile Tab, [Area] Compose

#3255 Migrate Profile screen to Compose UI
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/EndOfYearPromptCard.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt
  modules/features/profile/src/main/res/layout-land/fragment_profile.xml
  modules/features/profile/src/main/res/layout/fragment_profile.xml
  modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt
  modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt
Labels: [Type] Tech Debt, [Area] Profile Tab, [Area] Compose

#3257 Use played up to time for longest episode calculation
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EndOfYearDao.kt
Labels: [Project] End of Year, [Type] Enhancement

#3256 Improve syncing of deselected chapters
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: [Type] Bug, [Area] Sync

#3262 [Tooling] Update `Dangerfile` to run Rubocop with `bundle exec`
  Dangerfile
Labels: [Type] Tooling, [Area] Tooling

#3265 Merge/release 7.77 into main
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerTest.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-ca/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EndOfYearDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: releases

#3260 Profile screen cleanup
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileHeader.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfilePage.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileSections.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileStats.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt
  modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt
  modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Devices.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
Labels: [Type] Tech Debt, [Area] Profile Tab, [Area] Compose

#3266 Do not stop view setup when there is no toolbar
  CHANGELOG.md
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
Labels: [Type] Bug, [Area] Automotive

#3267 Remove effects bug fix from 7.78 changelog
  CHANGELOG.md
Labels: [Type] Other, [Area] Documentation

#3254 Migrate player controls to Compose
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerClickListener.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerControlsHelper.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/playercontrols/PlayerControls.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout-land/adapter_player_header.xml
  modules/features/player/src/main/res/layout-sw600dp/adapter_player_header.xml
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/features/player/src/main/res/layout/player_controls.xml
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModelTest.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/AnimatedPlayPauseButton.kt
  modules/services/ui/src/main/res/raw/large_play_button.json
Labels: [Type] Tech Debt, [Area] Compose

#3261 Migrate to `about libraries` in mobile app
  app/build.gradle.kts
  app/lint-baseline.xml
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  gradle/libs.versions.toml
  modules/features/settings/build.gradle.kts
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LicensesFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
Labels: [Type] Enhancement, [Area] Settings

#3273 Fix shelf row position for tablet
  modules/features/player/src/main/res/layout-sw600dp/adapter_player_header.xml
Labels: [Type] Bug, [Area] Compose

#3276 Fix release version and bump release toolkit
  Gemfile.lock
  version.properties
Labels: [Type] Tooling, [Area] Tooling

#3278 Revert Compose ConstraintLayout bump
  gradle/libs.versions.toml
Labels: [Type] Bug, [Area] Wear OS, [Area] Compose

#3280 Clean up plural translations
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-ca/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
Labels: [Type] Other, [Area] Accessibility

#3282 Merge release/7.78 into main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#3285 Fix episode not loading on Wear OS
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
Labels: [Type] Bug, [Area] Wear OS

#3286 Do not request orientation in StoriesActivity
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt
Labels: [Type] Bug, [Project] End of Year

#3287 Merge/release 7.77.1 into 7.78
  metadata/release_notes.txt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
  version.properties
Labels: releases

#3288 Merge release/7.78 into main
  metadata/release_notes.txt
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
  version.properties
Labels: releases

#3269 Migrate player heading section to Compose
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ChapterProgressCircle.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerClickListener.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/ChapterProgressCircle.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/PlayerControls.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/PlayerHeadingSection.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout-land/adapter_player_header.xml
  modules/features/player/src/main/res/layout-sw600dp/adapter_player_header.xml
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/ComposeView.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
Labels: [Type] Tech Debt, [Area] Player UI, [Area] Compose

#3290 Remove deprecated SubscriptionType type
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/SignInStateTest.kt
  modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/UpNextViewModelTest.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/SubCancelledFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
  modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModelTest.kt
  modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModelTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SubscriptionStatus.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionTier.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionType.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
Labels: [Type] Tech Debt, [Area] Subscriptions

#3293 Remove redundant subscription code
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeButton.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersHeader.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModelTest.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/UpsellButtonTitle.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SubscriptionBadge.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserAvatar.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionTier.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: [Type] Tech Debt, [Area] Compose

#3294 Migrate account screen header to Compose UI
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountHeader.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
  modules/features/profile/src/main/res/layout-car/fragment_account_details.xml
  modules/features/profile/src/main/res/layout-car/view_expanded_user.xml
  modules/features/profile/src/main/res/layout/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/view_expanded_user.xml
  modules/features/profile/src/main/res/values-car/dimens.xml
  modules/features/profile/src/main/res/values/dimens.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserAvatar.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
Labels: [Type] Tech Debt, [Area] Compose

#3295 Migrate account details to Compose UI
  modules/features/account/src/main/res/values/dimens.xml
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountSections.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/SubCancelledFragment.kt
  modules/features/profile/src/main/res/layout-car/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/fragment_cancelled_sub.xml
  modules/features/profile/src/main/res/layout/fragment_trial_finished.xml
  modules/services/images/src/main/res/drawable/ic_newsletter.xml
  modules/services/images/src/main/res/drawable/ic_privacy_policy.xml
  modules/services/images/src/main/res/drawable/ic_terms_conditions.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
  modules/services/views/src/main/res/drawable/ic_delete.xml
Labels: [Type] Tech Debt, [Area] Compose

#3299 Migrate AccountDetailsFragment to Compose UI
  CHANGELOG.md
  app/lint-baseline.xml
  automotive/lint-baseline.xml
  lint.xml
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsPage.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/res/layout-car/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/activity_add_file.xml
  modules/features/profile/src/main/res/layout/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/fragment_change_email.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Devices.kt
  wear/lint-baseline.xml
Labels: [Type] Tech Debt, [Area] Compose

#3296 [Up Next Shuffle] Adding whats new for Shuffle feature
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/SharingHeader.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/ShuffleHeader.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/services/images/src/main/res/drawable-xxxhdpi/whatsnew_bookmarks.webp
  modules/services/images/src/main/res/drawable/whats_new_sharing_card.webp
  modules/services/images/src/main/res/drawable/whats_new_sharing_instagram.xml
  modules/services/images/src/main/res/drawable/whats_new_sharing_telegram.xml
  modules/services/images/src/main/res/drawable/whats_new_sharing_tumblr.xml
  modules/services/images/src/main/res/drawable/whats_new_sharing_whatsapp.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
Labels: [Type] Other, [Project] Up Next Shuffle

#3300 Clean up Pocket Casts colors
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountSections.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PocketCastsColors.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/GradientRowButton.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PocketCastsPill.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserAvatar.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Brush.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
Labels: [Type] Tech Debt, [Area] Theme

#3301 Migrate Automotive profile header to Compose UI
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsFragment.kt
  automotive/src/main/res/layout/fragment_automotive_settings.xml
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsPage.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileHeader.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
  modules/features/profile/src/main/res/layout-car/view_user.xml
  modules/features/profile/src/main/res/layout-land-car/view_user.xml
  modules/features/profile/src/main/res/layout-land/view_user.xml
  modules/features/profile/src/main/res/layout/view_user.xml
  modules/features/profile/src/main/res/values-car/dimens.xml
  modules/features/profile/src/main/res/values/dimens.xml
  modules/services/ui/src/main/res/values/styles.xml
  modules/services/utils/build.gradle.kts
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/DateUtil.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Flow.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/extensions/FlowWindowedTest.kt
Labels: [Type] Tech Debt, [Area] Automotive

#3304 Fix font scaling
  modules/features/profile/src/main/res/values/color.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
  modules/services/ui/src/main/res/values/colors.xml
Labels: [Type] Bug, [Area] Accessibility

#3302 Migrate Trial Finished to Compose UI
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/TrialFinishedFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/TrialFinishedNotes.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/TrialFinishedPage.kt
  modules/features/profile/src/main/res/layout/fragment_trial_finished.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PocketCastsColors.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/GradientIcon.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Type] Tech Debt, [Area] Subscriptions

#3307 Move Brush Gradient to Pocket Casts Colors
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingWelcomePage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeButton.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeLayoutComponents.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallfeatures/UpgradeLayoutFeatures.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallreviews/UpgradeLayoutReviews.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PocketCastsColors.kt
Labels: [Type] Tech Debt, [Area] Subscriptions
