Repository Automattic/pocket-casts-android, pull requests merged in 2024-05, with the labels that each got.

#2146 Add feature flag for search bar in Podcasts tab
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
  modules/features/podcasts/src/main/res/menu/podcasts_menu.xml
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Up Next

#2143 Add empty state mini player
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt
  modules/features/player/src/main/res/layout/view_mini_player.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: Up Next

#2145 Update Search bar colors in Discover
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
  modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
  modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
  modules/features/discover/src/main/res/layout/fragment_discover.xml
  modules/features/discover/src/main/res/layout/row_category_pills.xml
Labels: Categories Redesign + Ads in Categories

#2150 Update status bar for discover
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
Labels: Categories Redesign + Ads in Categories

#2115 Sleep Timer: Add the option to select the number of chapters
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout/fragment_sleep.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
Labels: Sleep Timer

#2154 Update okhttp version
  gradle/libs.versions.toml
Labels: tech debt

#2156 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#2159 Update sleep timer toast message for end of episode
  modules/services/localization/src/main/res/values/strings.xml
Labels: Sleep Timer

#2157 Initialize `crashlogging`. Remove all project dependencies from this module.
  app/build.gradle.kts
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/utils/SentryHelperTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  automotive/build.gradle.kts
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
  gradle/libs.versions.toml
  modules/services/crashlogging/build.gradle.kts
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/CrashReportPermissionCheck.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/ExceptionsFilter.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/FilteringCrashLogging.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/ObserveUser.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/di/CrashLoggingModule.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/di/ProvideApplicationScope.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/ExceptionsFilterTest.kt
  modules/services/preferences/build.gradle.kts
  modules/services/repositories/build.gradle.kts
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/ObserveTrackableUser.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserSettingsCrashReportPermission.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SentryHelper.kt
  wear/build.gradle.kts
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
Labels: Tooling, unit-tests-exemption

#2162 Update skip icons for widgets
  modules/services/images/src/main/res/drawable/ic_widget_skip_back.xml
  modules/services/images/src/main/res/drawable/ic_widget_skip_forward.xml
Labels: Widgets

#2158 Migrate from direct Sentry usages to CrashLogging
  app/build.gradle.kts
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelperTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  base.gradle
  gradle/libs.versions.toml
  modules/features/discover/build.gradle.kts
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/endofyear/build.gradle.kts
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
  modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
  modules/features/profile/build.gradle.kts
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/settings/build.gradle.kts
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/DateTypeConverter.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/services/sharedtest/build.gradle.kts
  modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/FakeCrashLogging.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SentryHelper.kt
  modules/services/views/build.gradle.kts
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelper.kt
Labels: Tooling

#2166 Remove recent screen transitions from 7.63 beta
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
  modules/services/ui/src/main/res/transition/slide_in.xml
Labels: bug

#2160 Sleep Timer: Update custom time row label
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout/fragment_sleep.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: Sleep Timer

#2169 Do not truncate ads description
  modules/features/discover/src/main/res/layout/row_category_ad.xml
Labels: Categories Redesign + Ads in Categories

#2168 Unit tests for `crashlogging` related classes
  gradle/libs.versions.toml
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/BuildDataProvider.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/di/CrashLoggingModule.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProviderTest.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/fakes/FakeBuildDataProvider.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/fakes/FakeCrashReportPermissionCheck.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/fakes/FakeObserveUser.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/user/ObserveTrackableUserTest.kt
Labels: Tooling

#2170 Do not truncate ads description
  modules/features/discover/src/main/res/layout/row_category_ad.xml
Labels: Categories Redesign + Ads in Categories

#2171 Fix version code and version name
  version.properties
Labels: releases

#2172 Fix version code for 7.62.2
  version.properties
Labels: releases

#2174 Account for 7.62.2 when migrating artwork settings
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
Labels: polish

#2176 Merge release 7.63-rc-4 into main
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/res/layout/row_category_ad.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  modules/services/ui/src/main/res/transition/slide_in.xml
  version.properties
Labels: releases

#2140 Select min dimension for small widget
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
Labels: Widgets

#2180 Enable categories redesign feature flag by default
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Categories Redesign + Ads in Categories

#2164 Dispatch refresh state when refresh task is throttled
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
Labels: bug

#2184 Do not send background restricions errors to Sentry
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/FirebaseAnalyticsTracker.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
Labels: analytics

#2165 Update podcasts grid design
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderListRow.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/res/layout/adapter_podcast_grid.xml
  modules/features/podcasts/src/main/res/layout/adapter_podcast_list.xml
  modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/CountBadge.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/UiUtil.kt
  modules/services/views/src/main/res/values/dimens.xml
Labels: unit-tests-exemption, Up Next

#2186 Remove categories redesign feature flag and discover endpoint clean up
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/discover/src/main/res/layout-h560dp/item_carousel.xml
  modules/features/discover/src/main/res/layout/item_carousel.xml
  modules/features/discover/src/main/res/layout/row_carousel_list.xml
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListWebService.kt
Labels: Categories Redesign + Ads in Categories

#2196 Update discover events tracks to match with Web Player
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: analytics

#2191 Update toolbar
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
  modules/features/filters/src/main/res/layout/fragment_filters.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/CountBadge.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/AppBarLayout.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragment.kt
Labels: Up Next

#2190 Change widget previews
  modules/features/widgets/src/main/res/drawable-night/widget_player_large_preview.png
  modules/features/widgets/src/main/res/drawable-night/widget_player_medium_preview.png
  modules/features/widgets/src/main/res/drawable-night/widget_player_small_preview.png
  modules/features/widgets/src/main/res/drawable/widget_player_large_preview.png
  modules/features/widgets/src/main/res/drawable/widget_player_medium_preview.png
  modules/features/widgets/src/main/res/drawable/widget_player_small_preview.png
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_nondynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_nondynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_nondynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_nondynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/widget_player_large_preview.xml
  modules/features/widgets/src/main/res/layout/widget_player_medium_preview.xml
  modules/features/widgets/src/main/res/layout/widget_player_small_preview.xml
  modules/features/widgets/src/main/res/xml/large_player_widget.xml
  modules/features/widgets/src/main/res/xml/medium_player_widget.xml
  modules/features/widgets/src/main/res/xml/small_player_widget.xml
  modules/services/images/src/main/res/drawable/widget_player_large_preview.png
  modules/services/images/src/main/res/drawable/widget_player_medium_preview.png
  modules/services/images/src/main/res/drawable/widget_player_small_preview.png
  modules/services/localization/src/main/res/values/strings.xml
Labels: Widgets

#2194 Fix auto archiving episodes
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: bug

#2201 Fetch episodes refresh batch size from remote config
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
Labels: polish, high priority

#2195 Migrate auto archive podcast settings to Compose
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/res/xml/preference_podcast_auto_archive.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Settings.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/dialogs/RadioOptionsDialog.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/AutoArchiveAfterPlaying.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/AutoArchiveInactive.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Toolbar.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragment.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ToolbarColors.kt
Labels: unit-tests-exemption, enhancement

#2204 Up Next - Minor tweaks
  modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: Up Next

#2200 Minor Up Next page colour changes.
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ChapterProgressBar.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
  modules/features/player/src/main/res/layout/adapter_up_next_playing.xml
  modules/features/player/src/main/res/layout/fragment_upnext.xml
  modules/services/images/src/main/res/drawable-xhdpi/ic_reorder.xml
Labels: polish, Up Next

#2202 Make large widget header padding smaller
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
Labels: Widgets

#2205 Move badge overlay outside card view
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
Labels: bug

#2213 Enable up next in tab bar
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Up Next

#2207 Merge/release 7.63 into main
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
  version.properties
Labels: releases

#2215 Change widget's button background color
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
Labels: Widgets

#2197 Mini player updates
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
  modules/features/player/src/main/res/drawable/mini_player_play_background_32.xml
  modules/features/player/src/main/res/drawable/mini_player_play_background_48.xml
  modules/features/player/src/main/res/layout/view_mini_player.xml
  modules/features/player/src/main/res/raw/mini_player_play_button_32.json
  modules/features/player/src/main/res/raw/mini_player_play_button_48.json
  modules/features/player/src/main/res/values/dimens.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Up Next

#2214 Allow scroll behind mini player
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeEmailFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeEmailFragmentPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangePwdFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastListFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RegionSelectFragment.kt
  modules/features/discover/src/main/res/layout/podcast_grid_fragment.xml
  modules/features/discover/src/main/res/layout/podcast_list_fragment.xml
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/res/drawable/background_miniplayer_gradient.xml
  modules/features/player/src/main/res/layout/view_mini_player.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/features/profile/src/main/res/layout-land/fragment_profile.xml
  modules/features/profile/src/main/res/layout/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/fragment_profile.xml
  modules/features/profile/src/main/res/values/dimens.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoAddSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadFiltersFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/BetaFeaturesFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/ExportSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt
  modules/features/settings/src/main/res/layout/fragment_settings_appearance.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Labels: Up Next

#2218 Set yearly subscription as default selected
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
Labels: subscriptions

#2220 Make large widget non-scrollable
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetManager.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/LargePlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
Labels: Widgets

#2206 Fix: All categories text color sometimes getting painted with wrong color
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
Labels: bug

#2217 Add "What's New" widgets animation
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/NewWidgetsHeader.kt
  modules/services/images/src/main/res/drawable/ic_phone_idicator_icons.xml
  modules/services/images/src/main/res/drawable/whats_new_widgets.png
Labels: unit-tests-exemption, Widgets

#2216 Include new widgets in release builds
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/NewWidgetsHeader.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/features/widgets/src/debug/AndroidManifest.xml
  modules/features/widgets/src/debugProd/AndroidManifest.xml
  modules/features/widgets/src/main/AndroidManifest.xml
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/PlayerWidgetEpisode.kt
  modules/services/images/src/main/res/drawable/ic_phone_idicator_icons.xml
  modules/services/images/src/main/res/drawable/whats_new_widgets.png
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/AndroidManifest.xml
Labels: unit-tests-exemption, Widgets

#2222 Improve the folder label position
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditColorPage.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderListRow.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
Labels: bug

#2092 fix wrong Up Next removal message
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
Labels: bug

#2223 Sync with 7.64-rc-1
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#2203 Convert OldDataOpenHelper into Kotlin
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/DataOpenHelper.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/OldDataOpenHelper.java
Labels: enhancement

#2221 [Tooling] Run Danger on the Linter Agent
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
  Dangerfile
Labels: Tooling

#2224 Fix: Subscribe to a podcast makes the page jumps after a few seconds
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RemainingPodcastsAdapter.kt
Labels: bug

#2230 Fix folder size on large screens
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/UiUtil.kt
Labels: bug

#2231 Fix status page crash
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt
Labels: bug

#2179 Introduce performance monitoring
  build.gradle.kts
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt
  modules/services/servers/build.gradle.kts
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
Labels: Tooling, do not merge

#2242 ExoPlayer Cache: Improve error handling
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerCacheUtil.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
Labels: Media

#2226 Add Nova Launcher integration
  app/build.gradle.kts
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/nova/build.gradle.kts
  modules/features/nova/src/main/AndroidManifest.xml
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/ContextExtensions.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherBridge.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncLifecycleObserver.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherSubscribedPodcast.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  settings.gradle.kts
Labels: unit-tests-exemption, Nova Launcher

#2238 Sync new releases with Nova Launcher
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherNewEpisode.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: Nova Launcher

#2235 Fix: Android doesn't handle timestamp parameter in share links properly
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParser.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParserTest.kt
Labels: bug

#2239 Sync trending podcasts Nova Launcher
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherTrendingPodcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: Nova Launcher

#2244 Add fixing downloads option
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImplTest.kt
Labels: unit-tests-exemption, enhancement

#2246 Sleep timer: Add logs
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
Labels: Sleep Timer

#2251 Update bottom inset on application start
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
Labels: polish

#2252 Fix folder flickering
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt
Labels: polish

#2247 Enable dynamic widget colors by default
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
Labels: Widgets

#2240 Sync in progress episodes with Nova Launcher
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherInProgressEpisode.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: Nova Launcher

#2253 Fix/bookmarks episode not found
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: bug, unit-tests-exemption

#2258 Change cache playing episode feature flag key
  CHANGELOG.md
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Media

#2257 Shortcuts ANR
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: bug, unit-tests-exemption

#2262 Bump min sdk version to 24
  CHANGELOG.md
  dependencies.gradle.kts
Labels: enhancement

#2254 Fix Tesla artwork issue
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt
Labels: bug

#2268 Move fixing downloads to a background task
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/FixDownloadsWorker.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelperImpl.kt
Labels: unit-tests-exemption, enhancement

#2261 Open clip links in a web view
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParser.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParserTest.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/activity/WebViewActivity.kt
Labels: Reimagine Sharing

#2267 Get Exoplayer cache size from remote config
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerCacheUtil.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt
Labels: Media

#2269 Fix: Sleep timer end of an episode is not pausing before right before the end
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: bug

#2241 Sync recently played podcasts with the Nova Launcher
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherRecentlyPlayedPodcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: Nova Launcher

#2182 Introduce Encrypted Logging
  .configure
  .configure-files/secret.properties.enc
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
  base.gradle
  dependencies.gradle.kts
  gradle/libs.versions.toml
  modules/features/shared/build.gradle.kts
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionStatusProvider.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/di/SharedModule.kt
  modules/services/crashlogging/build.gradle.kts
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/ConnectionStatusProvider.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/InitializeRemoteLogging.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt
  modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/di/CrashLoggingModule.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/InitializeRemoteLoggingTest.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProviderTest.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/fakes/FakeCrashLogging.kt
  modules/services/crashlogging/src/test/java/au/com/shiftyjelly/pocketcasts/crashlogging/fakes/FakeEncryptedLogging.kt
  settings.gradle.kts
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
Labels: unit-tests-exemption, enhancement

#2260 Fix: OPML Import
  CHANGELOG.md
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt
Labels: bug

#2265 Add advanced setting to allow more seek accuracy
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModel.kt
  modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModelTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
Labels: Media

#2255 Fixing toolbar memory leaks
  app/build.gradle.kts
  automotive/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangePwdFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  settings.gradle.kts
  wear/build.gradle.kts
Labels: bug

#2271 Sync main with `7.64`
  CHANGELOG.md
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  version.properties
Labels: releases

#2272 Add unit tests for pre process OPML file
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/PreProcessOpmlFile.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/opml/PreProcessOpmlFileTest.kt
Labels: unit tests

#2273 Adding sleep timer config to general
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
Labels: Sleep Timer

#2275 Merge/release 7.65 into main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#2282 Use correct argument for episode limit string formatting
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
Labels: bug

#2284 Fix latest badge disappearing on podcasts list view
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
Labels: bug

#2278 Fix: Subscribe button is highlighted in green instead of gray in the carousel
  CHANGELOG.md
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
Labels: polish

#2283 Configure Lint to fail builds
  .buildkite/pipeline.yml
  app/lint-baseline.xml
  automotive/lint-baseline.xml
  base.gradle
  lint.xml
  modules/features/account/lint-baseline.xml
  modules/features/cartheme/lint-baseline.xml
  modules/features/discover/lint-baseline.xml
  modules/features/endofyear/lint-baseline.xml
  modules/features/filters/lint-baseline.xml
  modules/features/navigation/lint-baseline.xml
  modules/features/nova/lint-baseline.xml
  modules/features/player/lint-baseline.xml
  modules/features/podcasts/lint-baseline.xml
  modules/features/profile/lint-baseline.xml
  modules/features/search/lint-baseline.xml
  modules/features/settings/lint-baseline.xml
  modules/features/shared/lint-baseline.xml
  modules/features/taskerplugin/lint-baseline.xml
  modules/features/widgets/lint-baseline.xml
  modules/services/analytics/lint-baseline.xml
  modules/services/compose/lint-baseline.xml
  modules/services/crashlogging/lint-baseline.xml
  modules/services/images/lint-baseline.xml
  modules/services/localization/lint-baseline.xml
  modules/services/model/lint-baseline.xml
  modules/services/preferences/lint-baseline.xml
  modules/services/repositories/lint-baseline.xml
  modules/services/servers/lint-baseline.xml
  modules/services/sharedtest/lint-baseline.xml
  modules/services/ui/lint-baseline.xml
  modules/services/utils/lint-baseline.xml
  modules/services/views/lint-baseline.xml
  wear/lint-baseline.xml
Labels: Tooling

#2276 Migrate ShiftyTrimSilenceProcessor to Kotlin
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyAudioProcessorChain.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyTrimSilenceProcessor.java
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyTrimSilenceProcessor.kt
Labels: tech debt, unit-tests-exemption

#2286 Fix: Search Term Persists When Navigating to Different Podcast Page
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeSearchView.kt
Labels: bug

#2289 Merge/release 7.65 rc 2 into main
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  version.properties
Labels: releases

#2292 Add logs to track negative seek on sync
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
Labels: Media
