Repository Automattic/pocket-casts-android, pull requests merged in 2024-06, with the labels that each got.

#2297 Fix podcast title talkback
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/features/podcasts/src/main/res/layout/adapter_podcast_grid.xml
Labels: bug

#2288 Update baseline Lint rules
  .buildkite/pipeline.yml
  app/lint-baseline.xml
  modules/features/profile/lint-baseline.xml
  modules/features/taskerplugin/lint-baseline.xml
  modules/services/images/lint-baseline.xml
Labels: Tooling

#2298 Merge 7.65-rc-3 into main
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
  modules/features/podcasts/src/main/res/layout/adapter_podcast_grid.xml
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  version.properties
Labels: releases

#2299 Bump `aboutlibraries` to `11.2.1`
  app/lint-baseline.xml
  automotive/lint-baseline.xml
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveLicensesFragment.kt
  gradle/libs.versions.toml
  modules/features/account/lint-baseline.xml
  modules/features/cartheme/lint-baseline.xml
  modules/features/discover/lint-baseline.xml
  modules/features/endofyear/lint-baseline.xml
  modules/features/filters/lint-baseline.xml
  modules/features/navigation/lint-baseline.xml
  modules/features/nova/lint-baseline.xml
  modules/features/player/lint-baseline.xml
  modules/features/podcasts/lint-baseline.xml
  modules/features/profile/lint-baseline.xml
  modules/features/search/lint-baseline.xml
  modules/features/settings/lint-baseline.xml
  modules/features/shared/lint-baseline.xml
  modules/features/taskerplugin/lint-baseline.xml
  modules/features/widgets/lint-baseline.xml
  modules/services/analytics/lint-baseline.xml
  modules/services/compose/lint-baseline.xml
  modules/services/crashlogging/lint-baseline.xml
  modules/services/images/lint-baseline.xml
  modules/services/localization/lint-baseline.xml
  modules/services/model/lint-baseline.xml
  modules/services/preferences/lint-baseline.xml
  modules/services/repositories/lint-baseline.xml
  modules/services/servers/lint-baseline.xml
  modules/services/sharedtest/lint-baseline.xml
  modules/services/ui/lint-baseline.xml
  modules/services/utils/lint-baseline.xml
  modules/services/views/lint-baseline.xml
  wear/lint-baseline.xml
Labels: Tooling

#2302 Grid UI tweaks
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/CountBadge.kt
  modules/services/views/src/main/res/values/dimens.xml
Labels: polish

#2317 Fix discover carousel analytics
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
Labels: analytics

#2310 Change up next tab position
  modules/services/views/src/main/res/menu/navigation.xml
Labels: Up Next

#2304 Bump measure-builds to 3.0.0
  app/lint-baseline.xml
  automotive/lint-baseline.xml
  build.gradle.kts
  gradle/libs.versions.toml
  modules/features/account/lint-baseline.xml
  modules/features/cartheme/lint-baseline.xml
  modules/features/discover/lint-baseline.xml
  modules/features/endofyear/lint-baseline.xml
  modules/features/filters/lint-baseline.xml
  modules/features/navigation/lint-baseline.xml
  modules/features/nova/lint-baseline.xml
  modules/features/player/lint-baseline.xml
  modules/features/podcasts/lint-baseline.xml
  modules/features/profile/lint-baseline.xml
  modules/features/search/lint-baseline.xml
  modules/features/settings/lint-baseline.xml
  modules/features/shared/lint-baseline.xml
  modules/features/taskerplugin/lint-baseline.xml
  modules/features/widgets/lint-baseline.xml
  modules/services/analytics/lint-baseline.xml
  modules/services/compose/lint-baseline.xml
  modules/services/crashlogging/lint-baseline.xml
  modules/services/images/lint-baseline.xml
  modules/services/localization/lint-baseline.xml
  modules/services/model/lint-baseline.xml
  modules/services/preferences/lint-baseline.xml
  modules/services/repositories/lint-baseline.xml
  modules/services/servers/lint-baseline.xml
  modules/services/sharedtest/lint-baseline.xml
  modules/services/ui/lint-baseline.xml
  modules/services/utils/lint-baseline.xml
  modules/services/views/lint-baseline.xml
  wear/lint-baseline.xml
Labels: Tooling

#2319 Configure threshold for negative seek on sync using Firebase remote config
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
Labels: analytics

#2308 Bump `rexml` to `3.2.8` and `wpmreleasetoolkit` to `11.0.2`
  Gemfile.lock
Labels: Tooling

#2313 Fix Lint issues
  app/lint-baseline.xml
  automotive/lint-baseline.xml
  base.gradle
  lint.xml
  modules/features/account/lint-baseline.xml
  modules/features/cartheme/lint-baseline.xml
  modules/features/discover/lint-baseline.xml
  modules/features/endofyear/lint-baseline.xml
  modules/features/filters/lint-baseline.xml
  modules/features/navigation/lint-baseline.xml
  modules/features/nova/lint-baseline.xml
  modules/features/player/lint-baseline.xml
  modules/features/podcasts/lint-baseline.xml
  modules/features/profile/lint-baseline.xml
  modules/features/search/lint-baseline.xml
  modules/features/settings/lint-baseline.xml
  modules/features/shared/lint-baseline.xml
  modules/features/taskerplugin/lint-baseline.xml
  modules/features/widgets/lint-baseline.xml
  modules/features/widgets/src/main/res/drawable-night-nodpi/widget_player_large_preview.png
  modules/features/widgets/src/main/res/drawable-night-nodpi/widget_player_medium_preview.png
  modules/features/widgets/src/main/res/drawable-night-nodpi/widget_player_small_preview.png
  modules/features/widgets/src/main/res/drawable-nodpi/widget_player_large_preview.png
  modules/features/widgets/src/main/res/drawable-nodpi/widget_player_medium_preview.png
  modules/features/widgets/src/main/res/drawable-nodpi/widget_player_small_preview.png
  modules/services/analytics/lint-baseline.xml
  modules/services/compose/lint-baseline.xml
  modules/services/crashlogging/lint-baseline.xml
  modules/services/images/lint-baseline.xml
  modules/services/images/src/main/res/drawable-xhdpi/appicon_patron_glow.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_patron_chrome.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_patron_dark.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_patron_glow.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_patron_round.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_pride_2023.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_radioactive.png
  modules/services/images/src/main/res/drawable-xxhdpi/appicon_red_velvet.png
  modules/services/localization/lint-baseline.xml
  modules/services/model/lint-baseline.xml
  modules/services/preferences/lint-baseline.xml
  modules/services/repositories/lint-baseline.xml
  modules/services/servers/lint-baseline.xml
  modules/services/sharedtest/lint-baseline.xml
  modules/services/ui/lint-baseline.xml
  modules/services/utils/lint-baseline.xml
  modules/services/views/lint-baseline.xml
  wear/lint-baseline.xml
Labels: HACK week

#2279 Update targetSdk version to 34
  CHANGELOG.md
  dependencies.gradle.kts
  gradle/libs.versions.toml
  modules/features/profile/lint-baseline.xml
  modules/services/views/lint-baseline.xml
  modules/services/views/src/main/res/layout/discover_podcast_adapter.xml
  wear/lint-baseline.xml
  wear/src/main/AndroidManifest.xml
Labels: Android 14

#2309 Add database export option
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/HelpViewModel.kt
  modules/features/settings/src/main/res/menu/menu_help.xml
  modules/services/images/lint-baseline.xml
  modules/services/images/src/main/res/drawable/ic_external.xml
  modules/services/localization/lint-baseline.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/DatabaseExportHelper.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/support/DatabaseExportHelperTest.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtilWrapper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/OpmlExporter.kt
Labels: HACK week

#2301 Bump Gradle and AGP
  app/build.gradle.kts
  app/lint-baseline.xml
  automotive/build.gradle.kts
  base.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  modules/features/account/lint-baseline.xml
  modules/features/endofyear/lint-baseline.xml
  modules/features/player/lint-baseline.xml
  modules/features/podcasts/lint-baseline.xml
  modules/features/profile/lint-baseline.xml
  modules/features/settings/lint-baseline.xml
  modules/features/widgets/lint-baseline.xml
  modules/services/compose/lint-baseline.xml
  modules/services/localization/lint-baseline.xml
  modules/services/model/lint-baseline.xml
  modules/services/repositories/lint-baseline.xml
  modules/services/servers/lint-baseline.xml
  modules/services/utils/lint-baseline.xml
  modules/services/views/lint-baseline.xml
  wear/build.gradle.kts
  wear/lint-baseline.xml
Labels: Tooling

#2324 Attempt to fix app freezing when writing several podcast episodes to WAL
  CHANGELOG.md
  modules/features/podcasts/src/main/res/layout/adapter_episode.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
  modules/services/views/src/main/res/layout/view_file_status_icons.xml
Labels: bug

#2306 Migrate AutoArchiveFragment to Jetpack Compose
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchivePage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
  modules/features/settings/src/main/res/xml/preferences_auto_archive.xml
Labels: tech debt

#2315 Move chapter selection to chapter manager
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoSelectionTest.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImplTest.kt
Labels: HACK week

#2316 Control chapter skipping from withing the player manager
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
  modules/services/repositories/lint-baseline.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: HACK week

#2318 Add chapters to episode details screen
  CHANGELOG.md
  lint.xml
  modules/features/player/lint-baseline.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
  modules/features/podcasts/lint-baseline.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragmentViewModel.kt
  modules/services/localization/lint-baseline.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: unit-tests-exemption, HACK week

#2326 Remove flickering when double-tapping an item in the tab bar
  CHANGELOG.md
  modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/BottomNavigator.kt
Labels: bug

#2323 Migrate Done screen to Jetpack Compose
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeDoneFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeDonePage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangeEmailFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangePwdFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/DoneViewModel.kt
  modules/features/account/src/main/res/layout/fragment_change_done.xml
Labels: tech debt, unit-tests-exemption

#2328 Include media meta-data needed for automotive media app
  automotive/src/main/AndroidManifest.xml
  automotive/src/main/res/xml/automotive_app_desc.xml
Labels: automotive

#2329 Merge/release 7.65 into main
  automotive/src/main/AndroidManifest.xml
  automotive/src/main/res/xml/automotive_app_desc.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#2330 Do not use Timer in StoriesViewModel
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
Labels: bug

#2332 Merge release/7.66-rc-1 into main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#2325 Add Download episode action to shelf list in Now Playing
  CHANGELOG.md
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout/adapter_shelf_item.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/PlayButtonListener.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfItem.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/WarningsHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
Labels: polish

#2338 Use latest Nova SDK to sync subscribed podcasts
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
  modules/features/nova/build.gradle.kts
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherSubscribedPodcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: Nova Launcher

#2340 Fix: Listening History - event not track when tap on clean listening history
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: bug, analytics

#2336 Wear app: Bring back email login for debug build
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/AuthenticationNavGraph.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithEmailScreen.kt
Labels: wear os

#2312 Migrate change password screen to Jetpack Compose
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangePasswordPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ChangePwdFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ChangePwdViewModel.kt
  modules/features/account/src/main/res/layout-car/fragment_change_pwd.xml
  modules/features/account/src/main/res/layout-land-car/fragment_change_pwd.xml
  modules/features/account/src/main/res/layout-land/fragment_change_pwd.xml
  modules/features/account/src/main/res/layout/fragment_change_pwd.xml
Labels: tech debt

#2353 Revert #2286 in order to avoid Search Term gets cleared when scrolled off-screen issue
  CHANGELOG.md
  metadata/release_notes.txt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeSearchView.kt
Labels: bug

#2355 Bump Tasker plugin
  gradle/libs.versions.toml
  modules/features/taskerplugin/build.gradle.kts
Labels: do not merge, Android 14, tasker

#2356 Revert PR 2326
  CHANGELOG.md
  metadata/release_notes.txt
  modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/BottomNavigator.kt
Labels: bug

#2357 Make chapter indices 0 based
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/96.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
Labels: bug

#2358 Merge release/7.66-rc-2
  CHANGELOG.md
  gradle/libs.versions.toml
  metadata/release_notes.txt
  modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/BottomNavigator.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeSearchView.kt
  modules/features/taskerplugin/build.gradle.kts
  version.properties
Labels: releases

#2343 Sync trending podcasts with Nova
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: Nova Launcher

#2345 Sync new releases with Nova
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: Nova Launcher

#2346 Sync in progress episodes with Nova
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: Nova Launcher

#2347 Sync recently played podcasts with Nova
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherRecentlyPlayedPodcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: Nova Launcher

#2348 Refactor creating Nova Launcher intents
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
Labels: Nova Launcher

#2351 Rename both track name event and property for Headphone Controls
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: analytics

#2377 Add sharing clips option
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt
  modules/features/player/src/main/res/layout/fragment_share.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt
Labels: Reimagine Sharing

#2362 Update Privacy Track event name
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: analytics

#2376 Fix episode sharing action when using multi-selection
  CHANGELOG.md
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
Labels: bug

#2361 Sync Up Next queue with Nova Launcher
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherBridge.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherQueueSync.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
  modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/SubmissionResult.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheetFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/LargePlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/MediumPlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/SmallPlayerWidgetState.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/97.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherQueueEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
Labels: unit-tests-exemption, Nova Launcher

#2381 Track `up_next_shown ` when tapping on navigation bar
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
Labels: bug, analytics

#2383 Add properties to `bookmark_created ` track event
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
Labels: analytics

#2388 Merge release 7.66 into main
  CHANGELOG.md
  automotive/lint-baseline.xml
  modules/features/account/lint-baseline.xml
  modules/services/localization/lint-baseline.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#2378 Cache playing episode feature flag + advanced setting
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModel.kt
  modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModelTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerCacheUtil.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: unit-tests-exemption, Media

#2391 Ignore all Lint rules in the localization module
  base.gradle
  lint-no-op.xml
  modules/services/localization/lint-baseline.xml
Labels: Tooling

#2390 Track playback_failed event
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: analytics

#2387 Fix: Track `discover_featured_page_changed` event only when Discover is visible
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
Labels: bug, analytics

#2380 Cache playing episode
  CHANGELOG.md
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CacheWorker.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt
Labels: unit-tests-exemption, Media

#2384 Play clips on clip page
  modules/features/clip/build.gradle.kts
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/Clip.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipCard.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipColors.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipModule.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipPlayer.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipSelector.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt
  modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/FakeClipPlayer.kt
  modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModelTest.kt
Labels: unit-tests-exemption, Reimagine Sharing

#2393 Merge/release 7.67 into main
  CHANGELOG.md
  Gemfile.lock
  metadata/release_notes.txt
  version.properties
Labels: releases

#2385 Share clip links
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt
Labels: Reimagine Sharing

#2386 Add landscape orientation for clip sharing
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/HorizontalClipCard.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt
  modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/VerticalClipCard.kt
  modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModelTest.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
Labels: Reimagine Sharing

#2396 Add `chapter_link_clicked` event
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: analytics

#2397 Add `filter_options_modal_option_tapped` event
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: analytics

#2394 Add `source ` to `episode_download_finished `
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/PlayButtonListener.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudBottomSheetViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/NotificationBroadcastReceiver.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncJob.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/WarningsHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
Labels: bug, analytics

#2399 Transcripts - Add feature flag
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Podcast Standard Tags, Transcripts

#2401 Discover - Update carousel title size
  CHANGELOG.md
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselItemViewHolder.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RankedListAdapter.kt
  modules/features/discover/src/main/res/layout-h560dp/item_carousel.xml
  modules/features/discover/src/main/res/layout/item_carousel.xml
Labels: bug

#2402 Add missing auto play track events
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: analytics

#2407 Fix sharing null time marks in episode
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt
Labels: bug

#2408 Merge/release 7.67 into main
  CHANGELOG.md
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselItemViewHolder.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RankedListAdapter.kt
  modules/features/discover/src/main/res/layout-h560dp/item_carousel.xml
  modules/features/discover/src/main/res/layout/item_carousel.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
  version.properties
Labels: releases
