Repository Automattic/pocket-casts-android, pull requests merged in 2024-03, with the labels that each got.

#1897 Remove Firebase source for settings sync flag
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: high priority, releases, sync settings

#1898 Subscription - Update replacement mode
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
Labels: subscriptions

#1895 Deselect Chapters - Add to list of features
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/services/images/src/main/res/drawable/ic_tick_circle_filled.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: unit-tests-exemption, Deselecting Chapters

#1900 Merge release 7.58 to main
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  version.properties
Labels: releases

#1896 Deselect Chapters - What's new
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/DeselectChaptersHeader.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/services/images/src/main/res/drawable/whats_new_deselect_chapters_selected.xml
  modules/services/images/src/main/res/drawable/whats_new_deselect_chapters_unselected.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: Deselecting Chapters

#1902 Sync RSS artwork setting
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1904 Merge release 7.59 to main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#1814 Update Compose and other libraries
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
  base.gradle
  gradle/libs.versions.toml
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingCreateAccountPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingForgotPasswordPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingWelcomePage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/import/OnboardingImportFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/import/OnboardingImportFrom.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/import/OnboardingImportStartPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsFlow.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreatePodcastsPage.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/SystemBarsStyles.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/ThemedTopAppBar.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/AutoResizeText.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/FolderColorPicker.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/extensions/MediaMetadataCompatExt.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyAudioProcessorChain.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyRenderersFactory.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyTrimSilenceProcessor.java
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/MainCoroutineRule.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/di/WearAppModule.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/NowPlayingChip.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/AuthenticationNavGraph.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NowPlayingPager.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/WatchListChip.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/PauseButtonStyled.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/PlayButtonStyled.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/PlayPauseButtonStyled.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/PodcastControlButtonsStyled.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/SeekForwardButtonStyled.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/SetVolumeButtonStyled.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/AudioOutputSelectorHelper.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingViewModel.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsRoutes.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/UrlScreen.kt
Labels: tech debt

#1905 Revert custom cache system implementation
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/89.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Power.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: tech debt

#1909 Add remote config for settings sync flag
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: sync settings

#1912 Improve episode download failure analytics
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadError.kt
  modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadErrorTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadResult.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/ResponseValidationResult.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Network.kt
Labels: analytics

#1910 Configure app to cache episodes when playing using Exoplayer Cache
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Media

#1906 Remove unused adapters, disable `databinding` from modules that don't use it
  modules/features/account/build.gradle.kts
  modules/features/discover/build.gradle.kts
  modules/features/endofyear/build.gradle.kts
  modules/features/filters/build.gradle.kts
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/BindingAdapters.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/BindingAdapters.kt
  modules/features/profile/build.gradle.kts
  modules/features/settings/build.gradle.kts
  modules/features/shared/build.gradle.kts
  modules/features/taskerplugin/build.gradle.kts
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt
Labels: tech debt

#1914 Align download failure event with the latest design
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadError.kt
  modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadErrorTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadResult.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
Labels: analytics

#1917 Add stale downloads analytics event
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  base.gradle
  gradle/libs.versions.toml
  modules/features/shared/build.gradle.kts
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/DownloadStatisticsReporter.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/DownloadStatisticsReporterTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTrackerWrapper.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/InstantConverter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/EpisodeDownloadFailureStatistics.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/InstantConverterTest.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/SafeDateTypeConverterTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/Annotations.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
Labels: analytics

#1920 Bump media3 to 1.1.1
  gradle/libs.versions.toml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyAudioProcessorChain.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyRenderersFactory.kt
Labels: tech debt

#1911 Migrate Player Header from data binding
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/BindingAdapters.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/res/layout-land/adapter_player_header.xml
  modules/features/player/src/main/res/layout/adapter_player_header.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt
Labels: tech debt

#1922 Merge/release 7.59 into main
  Gemfile.lock
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  base.gradle
  fastlane/Fastfile
  gradle/libs.versions.toml
  modules/features/shared/build.gradle.kts
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/DownloadStatisticsReporter.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/DownloadStatisticsReporterTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTrackerWrapper.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadError.kt
  modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadErrorTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/InstantConverter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/EpisodeDownloadFailureStatistics.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/InstantConverterTest.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/SafeDateTypeConverterTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/Annotations.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadResult.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/ResponseValidationResult.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Network.kt
  version.properties
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
Labels: releases

#1915 Migrate Video from data binding
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/BindingAdapters.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
  modules/features/player/src/main/res/layout/fragment_video.xml
Labels: tech debt

#1923 Migrate next playing adapter from data binding
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
  modules/features/player/src/main/res/layout/adapter_up_next.xml
  modules/features/player/src/main/res/layout/adapter_up_next_footer.xml
  modules/features/player/src/main/res/layout/adapter_up_next_playing.xml
  modules/features/player/src/main/res/layout/view_up_next_action.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt
Labels: tech debt

#1924 Migrate mini player from data binding
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
  modules/features/player/src/main/res/layout/view_mini_player.xml
Labels: tech debt

#1927 Migrate device scoped settings to global settings
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#1926 Use activity instead of fragment manager for multi-selection
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectHelper.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt
Labels: tech debt

#1931 Upgrade coroutines to `1.8.1-Beta`
  gradle/libs.versions.toml
Labels: tech debt, high priority

#1928 Migrate notes from data binding
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt
  modules/features/player/src/main/res/layout/fragment_notes.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt
Labels: tech debt

#1913 Migrate Sleep from data binding
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
  modules/features/player/src/main/res/layout/fragment_sleep.xml
Labels: tech debt

#1932 Player update release time out
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
Labels: bug

#1935 [Fix] Categories tapping
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesListRowAdapter.kt
Labels: bug

#1937 Migrate episode container from data binding
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/res/layout/fragment_episode_container.xml
Labels: tech debt

#1934 Migrate podcast header top from data binding
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/features/podcasts/src/main/res/layout-land/view_podcast_header_top.xml
  modules/features/podcasts/src/main/res/layout/adapter_podcast_header.xml
  modules/features/podcasts/src/main/res/layout/view_podcast_header_top.xml
Labels: tech debt

#1933 Add playedUpTo tag for illegal playback state error
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: enhancement

#1944 Migrate podcast fragment from data binding
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/res/layout/fragment_podcast.xml
Labels: tech debt

#1916 Deselect Chapters - Sync
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/90.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/ChapterIndicesConverter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/ChapterIndices.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
  modules/services/protobuf/src/main/proto/sync_api.proto
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/PodcastEpisodesResponse.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
Labels: unit-tests-exemption, Deselecting Chapters

#1941 Migrate podcast header bottom from data binding
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/BindingAdapters.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/features/podcasts/src/main/res/layout/adapter_podcast_header.xml
  modules/features/podcasts/src/main/res/layout/view_podcast_header_bottom.xml
Labels: tech debt

#1936 Disable data binding in `player` module
  modules/features/player/build.gradle.kts
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/ViewExtensions.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
  modules/features/player/src/main/res/layout/view_player_bottom_sheet.xml
Labels: tech debt

#1938 Migrate episode view holders from data binding
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/UserEpisodeViewHolder.kt
  modules/features/podcasts/src/main/res/layout/adapter_episode.xml
  modules/features/podcasts/src/main/res/layout/adapter_user_episode.xml
Labels: tech debt

#1940 Deselect Chapters - What's new updates
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/BookmarksHeader.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Deselecting Chapters

#1946 Disable data binding in podcasts module
  modules/features/podcasts/build.gradle.kts
Labels: tech debt

#1942 Reduce recomposition count
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
Labels: bug, bookmarks

#1950 Merge release/7.59 into main
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  version.properties
Labels: releases

#1948 Remove unused binding adapters. Disable data binding in views module.
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/ViewExtensions.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/services/views/build.gradle.kts
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewExtensions.kt
Labels: tech debt

#1947 Migrate search fragment from data binding. Disable data binding in search module.
  modules/features/search/build.gradle.kts
  modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
  modules/features/search/src/main/res/layout/fragment_search.xml
Labels: tech debt

#1952 Do not sync any auto download related settings
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: high priority, sync settings

#1953 fix: remove unused binding adapters for podcasts module
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/BindingAdapters.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/ViewExtensions.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
Labels: bug, tech debt

#1954 Release/7.60
  CHANGELOG.md
  metadata/release_notes.txt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/BindingAdapters.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/ViewExtensions.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  version.properties
Labels: releases

#1945 Update categories pills UI
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesBottomSheet.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesBottomSheetAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesListRowAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesListRowRedesignAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPill.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
  modules/features/discover/src/main/res/drawable/ic_arrow_close.xml
  modules/features/discover/src/main/res/drawable/ic_arrow_down.xml
  modules/features/discover/src/main/res/drawable/ic_arrow_up.xml
  modules/features/discover/src/main/res/layout/category_pill.xml
  modules/features/discover/src/main/res/layout/item_category_redesign.xml
Labels: Categories Redesign + Ads in Categories

#1958 Disable data binding in the project 🎉
  app/build.gradle.kts
  automotive/build.gradle.kts
  wear/build.gradle.kts
Labels: tech debt

#1957 Fix What's New closing the app
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
Labels: bug

#1959 Process show notes asynchronously
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt
Labels: Podcast Standard Tags

#1960 Release/7.60
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  version.properties
Labels: releases

#1956 Redesign chapter models
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/to/ChapterTest.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
  modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/TimeHelper.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChapterTest.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChaptersTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/EpisodeFileMetadata.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/InMemoryFeatureFlagRule.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/InMemoryFeatureProvider.kt
Labels: Podcast Standard Tags

#1962 Add database model for chapters
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/91.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/DbChapter.kt
Labels: unit-tests-exemption, Podcast Standard Tags

#1964 Fetch chapters from standard tags
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateShowNotesTask.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt
Labels: unit-tests-exemption, Podcast Standard Tags

#1967 Display most popular podcasts by category
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesListRowRedesignAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPill.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/discover/src/main/res/layout/item_most_popular_podcasts.xml
  modules/features/discover/src/main/res/layout/row_most_popular_podcasts.xml
  modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/LocaliseHelper.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DiscoverModel.kt
Labels: unit-tests-exemption, Categories Redesign + Ads in Categories

#1965 Display remote chapters in the UI
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChapterTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PocketCastsImageRequestFactory.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/LocalPlayer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt
Labels: Podcast Standard Tags

#1969 Add alphabetical sort order for podcast episodes
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
Labels: enhancement

#1971 Fix chapters syncing
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
Labels: bug, high priority, Deselecting Chapters

#1972 Toggle chapter selection on title click
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
Labels: Deselecting Chapters

#1973 Fix cancellation info link
  CHANGELOG.md
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
Labels: bug

#1974 Release/7.60
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
  version.properties
Labels: releases

#1980 Discover redesign - Tracks
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/LargeListRowAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/SmallListRowAdapter.kt
Labels: Categories Redesign + Ads in Categories

#1982 [Categories Redesign] Update feature flag
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Categories Redesign + Ads in Categories

#1984 Implement Small Player widget
  app/build.gradle.kts
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  gradle/libs.versions.toml
  modules/features/widgets/build.gradle.kts
  modules/features/widgets/src/main/AndroidManifest.xml
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetManager.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetStateAdapter.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidgetReceiver.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/action/Actions.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/action/OpenPocketCastsAction.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/action/PausePlaybackAction.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/action/ResumePlaybackAction.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/PlayerWidgetEpisode.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/PlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/di/WidgetEntryPoint.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
  modules/features/widgets/src/main/res/xml/small_player_widget.xml
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/images/src/main/res/drawable-xhdpi/defaultartwork_small_rounded.png
  modules/services/images/src/main/res/drawable-xxhdpi/defaultartwork_small_rounded.png
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  settings.gradle.kts
Labels: unit-tests-exemption, Widgets

#1981 Display loading progress bar when is filtering Podcasts by Category
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesBottomSheet.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesBottomSheetAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/discover/src/main/res/layout/row_category_pills.xml
Labels: polish, unit-tests-exemption, Categories Redesign + Ads in Categories

#1989 Sanitize share list URL path segment
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/servers/ShareServerManagerImplTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingViewModel.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/list/ListServerManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/list/ListServerManagerImpl.kt
Labels: bug

#1990 Filter offers when have more than one available
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
Labels: bug

#1993 Release/7.60
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/servers/ShareServerManagerImplTest.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/list/ListServerManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/list/ListServerManagerImpl.kt
  version.properties
Labels: releases

#1995 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1996 build: apply Gradle Enterprise plugin. Enable remote build cache on CI
  gradle_build_cache.gradle.kts
  settings.gradle.kts
Labels: Tooling
