Repository Automattic/pocket-casts-android, pull requests merged in 2024-12, with the labels that each got.

#3305 Fix account header label weights
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountHeader.kt
Labels: [Type] Bug, [Area] Compose

#3308 Add the Trial Finished Compose UI migration to `main`
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/TrialFinishedFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/TrialFinishedNotes.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/TrialFinishedPage.kt
  modules/features/profile/src/main/res/layout/fragment_trial_finished.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/GradientIcon.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Type] Tech Debt, [Area] Subscriptions

#3310 [Tooling] Introduce lane to automate rollout update
  fastlane/Fastfile
Labels: [Type] Tooling, [Area] Tooling

#3303 [Auto Downloading] - Add the auto download toggle for new podcast following
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
  modules/features/settings/src/main/res/xml/preferences_auto_download.xml
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
Labels: [Type] Enhancement, [Project] Auto Downloading Episodes

#3309 Create NumberStepper component in Compose UI and replace it for Sleep Timer
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
  modules/features/player/src/main/res/layout/fragment_sleep.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/NumberStepper.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Type] Tech Debt, [Project] Sleep Timer

#3332 [Up Next Shuffle] - Add snackbar confirmation for when enabling shuffle
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Type] Enhancement, [Project] Up Next Shuffle

#3335 Merge release/7.78 into main
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
  fastlane/Fastfile
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
  modules/features/settings/src/main/res/xml/preferences_auto_download.xml
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-ca/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
  version.properties
Labels: releases

#3202 [Paywall Experiment] Set AB Experiment for 7.79
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Experiment.kt
Labels: [Project] Paywall Experiments, [Type] Core

#3333 [Tooling] Automate moving the PRs to next milestone during code-freeze
  Gemfile.lock
  fastlane/Fastfile
Labels: [Type] Tooling, [Area] Tooling

#3326 Fix edge-to-edge for the full-screen player
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/LongPressOptionsFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfRearrangeActionsPage.kt
  modules/features/player/src/main/res/layout/fragment_player_container.xml
  modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/NavigationBarColor.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/StatusBarIconColor.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/BottomSheetExt.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt
Labels: [Type] Tech Debt, [Area] Android 15

#3334 Improving the Up Next clear all button
  CHANGELOG.md
  modules/features/player/src/main/res/menu/upnext.xml
  modules/services/localization/src/main/res/values/strings.xml
Labels: [Type] Enhancement, [Area] Up Next

#3339 Position bookmark shelf item after podcast navigation item
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfRowItem.kt
Labels: [Priority] Medium, [Type] Enhancement, [Area] Player UI

#3336 Improve user log sharing
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/LogsViewModel.kt
  modules/features/settings/src/main/res/menu/menu_help.xml
Labels: [Type] Enhancement, [Area] Help & Feedback

#3340 Merge release/7.79 into main
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#3341 [Tooling] Fix `update_rollouts` failing on initial submission (draft -> inProgress)
  Gemfile
  Gemfile.lock
Labels: [Type] Tooling, [Area] Tooling

#3344 Revert "Bump androidx.constraintlayout:constraintlayout-compose from 1.0.1 to 1.1.0"
  gradle/libs.versions.toml
Labels: [Type] Bug, [Area] Network

#3343 [Auto Downloading] Add auto download on follow toggle to support file
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
Labels: [Type] Enhancement, [Project] Auto Downloading Episodes

#3345 Share Playback Stories in 9:16 aspect ratio
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoryCaptureController.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtil.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtilTest.kt
Labels: [Type] Bug, [Project] End of Year

#3347 Merge release/7.78.1 into release/7.79
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoryCaptureController.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtil.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtilTest.kt
  version.properties
Labels: releases

#3348 [Tooling] Point back to latest `fastlane`
  Gemfile
  Gemfile.lock
Labels: [Type] Tooling, [Area] Tooling

#3349 Merge release/7.79 into main
  Gemfile
  Gemfile.lock
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoryCaptureController.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtil.kt
  modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtilTest.kt
  version.properties
Labels: releases

#3342 Fix: Disabled global Auto download new episodes setting overrides podcast specifc one
  CHANGELOG.md
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
Labels: [Type] Bug, [Project] Auto Downloading Episodes

#3351 Do not use local files for ParcelFileDescriptor
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AlbumArtContentProvider.kt
Labels: [Type] Bug, [Priority] High, [Area] Playback, [Area] User Files

#3352 Task/release/7.79 backmerge
  Gemfile
  Gemfile.lock
Labels: releases

#3356 Fix issue where Champion information was not considered in the UI
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountHeader.kt
Labels: [Type] Bug, [Area] Profile Tab

#3363 [Tooling] Update GitHub Actions
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .github/workflows/gradle-wrapper-validation.yml
Labels: [Type] Tooling, [Area] Tooling

#3365 [Tooling] Update gemfile
  Gemfile.lock
Labels: [Type] Tooling, [Area] Tooling

#3357 Request permission before enabling Notify Me
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/NotificationPermissionHelper.kt
Labels: [Type] Enhancement, [Area] Notification

#3350 Don't show the notification permission request as the first screen
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/NotificationPermissionHelper.kt
Labels: [Type] Enhancement, [Area] Notification

#3366 Task/backmerge release 7.79
  Gemfile.lock
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountHeader.kt
  version.properties
Labels: releases

#3367 [Tooling] Update gems to latest versions
  Gemfile.lock
Labels: [Type] Tooling, [Area] Tooling

#3370 Merge release/7.79 into main
  Gemfile.lock
Labels: releases

#3376 [Tooling] Danger GitHub Actions configuration update
  .github/workflows/run-danger.yml
Labels: [Type] Tooling, [Area] Tooling

#3378 Fix podcast ratings not loading
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
Labels: [Type] Bug, [Area] Ratings

#3381 Merge release/7.79 into main
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
  version.properties
Labels: releases

#3377 Fix: Sleep timer stops podcast after given time
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModelTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerVolumeFadeOut.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerReceiver.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerState.kt
Labels: [Type] Bug, unit-tests-exemption, [Project] Sleep Timer

#3383 Converting user sync from Rx to Coroutines
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/FolderDaoTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/PromoCodeViewModel.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/FolderDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServiceManager.kt
Labels: [Type] Tech Debt, [Area] Sync

#3249 Use HTML in the podcast description
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/extensions/SpannedKtTest.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/105.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastResponse.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Spanned.kt
Labels: [Type] Enhancement, [Area] Podcast Page

#3387 Fix end of year translation
  CHANGELOG.md
  modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt
Labels: [Type] Bug, [Area] Translations i18n

#3385 [Manage Downloads] Allow users to dismiss low storage banner in download screen
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Labels: [Type] Enhancement, [Project] Manage Downloaded Episodes
