Repository Automattic/pocket-casts-android, pull requests merged in 2024-04, with the labels that each got.

#1999 Merge release/7.61-rc-1
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  metadata/release_notes.txt
  version.properties
Labels: releases

#2001 [Deselect Chapters] Remove it from Patron and update copies
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/services/localization/src/main/res/values/strings.xml
  version.properties
Labels: high priority

#2002 Merge/7.60.1 into 7.61
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/services/localization/src/main/res/values/strings.xml
  version.properties
Labels: releases

#2003 Merge/release 7.61 into main
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
  modules/services/localization/src/main/res/values/strings.xml
  version.properties
Labels: releases

#2010 Merge release/7.61-rc-3 into main
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyTrimSilenceProcessor.java
  version.properties
Labels: releases

#1998 Cleanup download task for cancelled episode download
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
Labels: bug

#2013 Do not allow to set podcast folder UUID to home folder UUID
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastTest.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/92.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt
Labels: bug, sync settings

#2005 Profile Bookmarks - Add menu and show empty screen
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt
Labels: bookmarks

#2020 Add widget installation analytics
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidgetReceiver.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetReceiver.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidgetReceiver.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/di/WidgetEntryPoint.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Labels: analytics, unit-tests-exemption, Widgets

#2014 Remove hardcoded categories setup
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastListFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DiscoverModel.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DisplayStyle.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/ExpandedStyle.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListWebService.kt
Labels: Categories Redesign + Ads in Categories

#2016 Fix playback state chapter indices update
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/entity/ChapterIndicesTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
Labels: Deselecting Chapters

#2019 Optimize data model for widgets
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/MediumPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetManager.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetStateAdapter.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/LargePlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/MediumPlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/PlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/SmallPlayerWidgetState.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
Labels: unit-tests-exemption, Widgets

#2022 Bookmark share
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarkAction.kt
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
Labels: bookmarks, unit-tests-exemption

#2023 Update search bar colors for new category design
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
  modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
  modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
  modules/features/discover/src/main/res/layout/row_category_pills.xml
Labels: Categories Redesign + Ads in Categories

#2034 Fix play button drawable update
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
Labels: bug

#2026 Profile bookmarks - Display & Sort
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksSortByDialog.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeListAdapter.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UserEpisodeDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/ProfileBookmark.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Bookmark.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/BookmarksSortTypeForProfile.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
Labels: bookmarks, unit-tests-exemption

#2029 Save embedded chapters in the database
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
Labels: enhancement

#2035 Update settings only if remote timestamp is greater than the local one
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: sync settings

#2036 Update podcast setting only if remote timestamp is greater than local one
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: bug, sync settings

#2033 Do not clear named setting modification timestamp
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/settings/advanced/AdvancedSettingsTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/utils/MutableClock.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/PromoCodeFragment.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
  modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingWelcomeViewModel.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsOptionsDialog.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaNotificationControlsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoAddSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
  modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt
  modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
  modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTracker.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/AppIcon.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsViewModel.kt
Labels: sync settings

#2037 Profile bookmarks - Add search
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoBookmarksInSearchView.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/search/BookmarkSearchHandler.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/search/BookmarkSearchHandlerTest.kt
  modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
Labels: bookmarks

#2024 Align widgets with design feedback
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PocketCastsLogo.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
  modules/features/widgets/src/main/res/xml/large_player_widget.xml
  modules/services/images/src/main/res/drawable/ic_widget_play.xml
  modules/services/images/src/main/res/drawable/ic_widget_skip_back.xml
  modules/services/images/src/main/res/drawable/ic_widget_skip_forward.xml
Labels: Widgets

#2042 Update Firebase emulator model
  fastlane/Fastfile
Labels: Tooling

#2039 Trim search term
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/search/BookmarkSearchHandler.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
Labels: bookmarks

#2044 Improve landscape player layout
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/res/layout-land/adapter_player_header.xml
Labels: bug

#2040 Make widgets accessible for small screens
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/features/widgets/src/main/res/xml/large_player_widget.xml
  modules/features/widgets/src/main/res/xml/medium_player_widget.xml
  modules/features/widgets/src/main/res/xml/small_player_widget.xml
  modules/services/images/src/main/res/drawable/widget_player_large_preview.png
  modules/services/images/src/main/res/drawable/widget_player_medium_preview.png
  modules/services/images/src/main/res/drawable/widget_player_small_preview.png
Labels: Widgets

#2038 Add widgets placeholders
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PocketCastsLogo.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
  modules/features/widgets/src/main/res/xml/large_player_widget.xml
  modules/features/widgets/src/main/res/xml/medium_player_widget.xml
  modules/features/widgets/src/main/res/xml/small_player_widget.xml
  modules/services/images/src/main/res/drawable-hdpi/ic_logo_background.png
  modules/services/images/src/main/res/drawable-hdpi/ic_logo_foreground.png
  modules/services/images/src/main/res/drawable-hdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-mdpi/ic_logo_background.png
  modules/services/images/src/main/res/drawable-mdpi/ic_logo_foreground.png
  modules/services/images/src/main/res/drawable-mdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-xhdpi/defaultartwork_small_rounded.png
  modules/services/images/src/main/res/drawable-xhdpi/ic_logo_background.png
  modules/services/images/src/main/res/drawable-xhdpi/ic_logo_foreground.png
  modules/services/images/src/main/res/drawable-xhdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-xxhdpi/defaultartwork_small_rounded.png
  modules/services/images/src/main/res/drawable-xxhdpi/ic_logo_background.png
  modules/services/images/src/main/res/drawable-xxhdpi/ic_logo_foreground.png
  modules/services/images/src/main/res/drawable-xxhdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-xxxhdpi/ic_logo_background.png
  modules/services/images/src/main/res/drawable-xxxhdpi/ic_logo_foreground.png
  modules/services/images/src/main/res/drawable-xxxhdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable/widget_player_large_preview.png
  modules/services/images/src/main/res/drawable/widget_player_medium_preview.png
  modules/services/images/src/main/res/drawable/widget_player_small_preview.png
  modules/services/localization/src/main/res/values/strings.xml
Labels: Widgets

#2046 Adjust corner size to 6 dp for widgets
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/services/images/src/main/res/drawable-hdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-mdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-xhdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-xxhdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable-xxxhdpi/ic_rounded_square.png
  modules/services/images/src/main/res/drawable/widget_player_large_preview.png
  modules/services/images/src/main/res/drawable/widget_player_medium_preview.png
Labels: Widgets

#2028 Profile bookmarks - Sync Sort Option
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
Labels: bookmarks

#2049 Merge release 7.61 into main
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/entity/ChapterIndicesTest.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
  version.properties
Labels: releases

#2050 Remove feature flag for profile bookmarks
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: bookmarks

#2051 Use shared debug key for signing debug app variants
  .gitignore
  base.gradle
  debug.keystore
Labels: Tooling

#2048 Sleep Timer: automatically restart if playback is resumed within 5 minutes
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
Labels: Sleep Timer

#2052 Merge/release 7.62 into main
  CHANGELOG.md
  Gemfile.lock
  metadata/release_notes.txt
  version.properties
Labels: releases

#2055 Update Release Toolkit from `10.0.0` to `11.0.1`
  Gemfile
  Gemfile.lock
Labels: Tooling

#2060 Fix crash when chapters have 0 length durations
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  fastlane/Fastfile
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
Labels: bug, high priority

#2057 Bump guava lib to latest
  gradle/libs.versions.toml
Labels: tech debt

#2053 Use epoch +1 second as a default sync timestamp
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
Labels: releases

#2061 Merge/release 7.61.1 into 7.62
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
  version.properties
Labels: releases

#2054 Sleep timer: Restart timer when shaking phone
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerReceiver.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
Labels: unit-tests-exemption, Sleep Timer

#2068 Merge/release 7.62 rc2 into main
  Gemfile.lock
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
  gradle/libs.versions.toml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
  modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
  version.properties
Labels: releases

#2064 [Tooling] Fix `new_beta_release` prompt, which can be misleading after a hotfix
  fastlane/Fastfile
Labels: Tooling

#2067 Do not take timestamp argument if it is missing
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
Labels: bug, bookmarks, Widgets

#2065 Make widget texts non scaling
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
  modules/features/widgets/src/main/res/layout/non_scaling_text.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_dynamic.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_dynamic_bold.xml
  modules/features/widgets/src/main/res/values-night/colors.xml
  modules/features/widgets/src/main/res/values/colors.xml
Labels: Widgets

#2071 Push large widget content to the bottom
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
Labels: Widgets

#2069 Sleep timer: Start fading out audio when sleep timer has 5 seconds left
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
Labels: Sleep Timer

#2072 Sleep Timer: Fix automatic restart when sleep timer dialog is open
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
Labels: bug, Sleep Timer

#2076 Allow medium widget to be resized to 3x1
  modules/features/widgets/src/main/res/xml/medium_player_widget.xml
Labels: Widgets

#2075 Fix: End of episode option is not being preserved when switching to another episode from Up Next
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Labels: bug, Sleep Timer

#2078 Merge/release 7.62 rc3 into main
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
  modules/features/widgets/src/main/res/layout/non_scaling_text.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_dynamic.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_dynamic_bold.xml
  modules/features/widgets/src/main/res/values-night/colors.xml
  modules/features/widgets/src/main/res/values/colors.xml
  modules/features/widgets/src/main/res/xml/medium_player_widget.xml
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  version.properties
Labels: releases

#2077 Replace search menu with search bar
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
  modules/features/podcasts/src/main/res/menu/podcasts_menu.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt
  modules/services/ui/src/main/res/drawable/search_background.xml
Labels: enhancement

#2084 Update DurationParceler.kt
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/parceler/DurationParceler.kt
Labels: bug

#2079 Sleep Timer: Play confirmation sound when restarting after shaking the phone
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
  modules/services/repositories/src/main/res/raw/sleep_time_device_shake_confirmation_sound.wav
Labels: Sleep Timer

#2088 Fix: Most Popular section missing padding top
  modules/features/discover/src/main/res/layout/row_most_popular_podcasts.xml
Labels: Categories Redesign + Ads in Categories

#2089 Fix media center low resolution image preview
  modules/services/repositories/src/main/AndroidManifest.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
Labels: bug

#2095 Bring back old widget and hide new ones
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  metadata/release_notes.txt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/features/widgets/src/main/AndroidManifest.xml
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/MediumPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/MediumPlayerWidgetReceiver.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/images/src/main/res/drawable-hdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_skip_forward.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_skip_forward.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_skip_forward.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_skip_forward.png
  modules/services/repositories/src/main/AndroidManifest.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/RemoteViewsTarget.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt
  modules/services/repositories/src/main/res/layout/widget.xml
  modules/services/repositories/src/main/res/layout/widget_default_theme.xml
  modules/services/repositories/src/main/res/layout/widget_dynamic_colors_theme.xml
  modules/services/repositories/src/main/res/values-v31/styles.xml
  modules/services/repositories/src/main/res/values/styles.xml
  modules/services/repositories/src/main/res/xml/widget.xml
Labels: unit-tests-exemption, Widgets

#2099 Merge/release 7.62 rc4 into main
  CHANGELOG.md
  app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
  metadata/release_notes.txt
  modules/features/discover/src/main/res/layout/row_most_popular_podcasts.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
  modules/features/widgets/src/main/AndroidManifest.xml
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/MediumPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/MediumPlayerWidgetReceiver.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/images/src/main/res/drawable-hdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-hdpi/widget_old_skip_forward.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-xhdpi/widget_old_skip_forward.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-xxhdpi/widget_old_skip_forward.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_nothing_loaded.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_pause.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_play.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_preview.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_skip_backward.png
  modules/services/images/src/main/res/drawable-xxxhdpi/widget_old_skip_forward.png
  modules/services/repositories/src/main/AndroidManifest.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/RemoteViewsTarget.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt
  modules/services/repositories/src/main/res/layout/widget.xml
  modules/services/repositories/src/main/res/layout/widget_default_theme.xml
  modules/services/repositories/src/main/res/layout/widget_dynamic_colors_theme.xml
  modules/services/repositories/src/main/res/values-v31/styles.xml
  modules/services/repositories/src/main/res/values/styles.xml
  modules/services/repositories/src/main/res/xml/widget.xml
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/parceler/DurationParceler.kt
  version.properties
Labels: releases

#2098 Prioritize embedded chapters
  CHANGELOG.md
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/93.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/DbChapter.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt
Labels: Podcast Standard Tags

#2100 Do not replace chapters if new ones are empty
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
Labels: enhancement, Podcast Standard Tags

#2082 Split episodes update into smaller batches
  CHANGELOG.md
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/RefreshResponse.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerResponseException.kt
  modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/refresh/RefreshPodcastBatcher.kt
  modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/RefreshResponseTest.kt
  modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/refresh/RefreshPodcastBatcherTest.kt
Labels: enhancement

#2097 Sleep Timer: Sleep time by episodes
  CHANGELOG.md
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
  modules/features/player/src/main/res/layout/fragment_sleep.xml
  modules/services/localization/src/main/res/values-ar/strings.xml
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-en-rGB/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nb/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/localization/src/main/res/values/strings.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerReceiver.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
Labels: Sleep Timer

#2103 Include widgets in debug builds
  modules/features/widgets/src/debug/AndroidManifest.xml
  modules/features/widgets/src/debugProd/AndroidManifest.xml
  modules/features/widgets/src/main/AndroidManifest.xml
Labels: Widgets

#2107 Save trending podcasts in the database
  app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
  modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/94.json
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
  modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/TrendingPodcast.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
Labels: enhancement

#2101 Move cast icon to the mini player
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
  modules/features/filters/src/main/res/menu/menu_filters.xml
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
  modules/features/player/src/main/res/layout/view_mini_player.xml
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/res/menu/podcasts_menu.xml
  modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Labels: Up Next

#2105 Add source to podcast details analytics
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastListFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingFragment.kt
  modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
  modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchResultsFragment.kt
  modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
Labels: analytics

#2108 Add subscribe button to most popular section and search bar color updates
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
  modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
  modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
  modules/features/discover/src/main/res/layout/item_most_popular_podcasts.xml
  modules/features/discover/src/main/res/layout/row_category_pills.xml
Labels: Categories Redesign + Ads in Categories

#2109 Merge/release 7.62 rc5 into main
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
  modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
  modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
  modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
  modules/features/discover/src/main/res/layout/item_most_popular_podcasts.xml
  modules/features/discover/src/main/res/layout/row_category_pills.xml
  modules/features/widgets/src/main/AndroidManifest.xml
  version.properties
Labels: releases

#2110 Do not set alpha and max lines via reflection
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/GlanceModifierExtensions.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_nondynamic_oneline_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_nondynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_nondynamic_twolines_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_nondynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_nondynamic_oneline_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_nondynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_nondynamic_twolines_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_nondynamic_twolines_transparent.xml
  modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Labels: bug, Widgets

#2117 Merge release/7.62 into main
  Gemfile.lock
  modules/services/localization/src/main/res/values-de/strings.xml
  modules/services/localization/src/main/res/values-es-rMX/strings.xml
  modules/services/localization/src/main/res/values-es/strings.xml
  modules/services/localization/src/main/res/values-fr-rCA/strings.xml
  modules/services/localization/src/main/res/values-fr/strings.xml
  modules/services/localization/src/main/res/values-it/strings.xml
  modules/services/localization/src/main/res/values-ja/strings.xml
  modules/services/localization/src/main/res/values-ko/strings.xml
  modules/services/localization/src/main/res/values-nl/strings.xml
  modules/services/localization/src/main/res/values-pt-rBR/strings.xml
  modules/services/localization/src/main/res/values-ru/strings.xml
  modules/services/localization/src/main/res/values-sv/strings.xml
  modules/services/localization/src/main/res/values-zh-rTW/strings.xml
  modules/services/localization/src/main/res/values-zh/strings.xml
  modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/refresh/RefreshPodcastBatcherTest.kt
  version.properties
Labels: releases

#2119 Account for updated prod version during settings migration
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
Labels: polish

#2128 Fix toolbar and title colors for profile bookmarks
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/res/layout/fragment_bookmarks_container.xml
Labels: bug, bookmarks

#2125 Include podcasts with corrupted folders when sorting by release date
  CHANGELOG.md
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
Labels: bug

#2113 Update profile navigation
  app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt
  modules/features/profile/src/main/res/layout/fragment_account_details.xml
  modules/features/profile/src/main/res/layout/fragment_profile.xml
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/ManualCleanupFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/CloseOnTabSwitch.kt
  modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
  modules/services/ui/src/main/res/transition/slide_in.xml
  modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Toolbar.kt
Labels: Up Next

#2124 Extract embedded image from a file when uploading it
  CHANGELOG.md
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
Labels: bug

#2112 Toggle episode artwork in different sections
  CHANGELOG.md
  modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeListAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/UserEpisodeViewHolder.kt
  modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
  modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt
  modules/features/settings/src/main/res/layout/fragment_settings_appearance.xml
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Settings.kt
  modules/services/localization/src/main/res/values/strings.xml
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesScreen.kt
  wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/downloads/DownloadsScreen.kt
Labels: enhancement, Podcast Standard Tags

#2131 Fix bookmarks episode title display
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
  modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
  modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt
  modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt
Labels: bookmarks

#2135 Merge release/7.63-rc-1
  CHANGELOG.md
  metadata/release_notes.txt
  version.properties
Labels: releases

#2129 Update widget themes to use secondary colors
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PocketCastsLogo.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_transparent.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_opaque.xml
  modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_transparent.xml
  modules/features/widgets/src/main/res/values/colors.xml
Labels: Widgets

#2130 Use rectangular rounded buttons in widgets
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackControls.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
  modules/services/images/src/main/res/drawable/rounded_rectangle.xml
Labels: Widgets

#2134 Add rounded corners on Android SDK < 31
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/GlanceModifierExtensions.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackControls.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/RounderCornerBox.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
Labels: Widgets

#2136 Resize large widget to available height
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidget.kt
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
  modules/features/widgets/src/main/res/xml/large_player_widget.xml
Labels: Widgets

#2137 Revert order of widget playback buttons
  modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackControls.kt
Labels: Widgets

#2139 Fix: Send ads event to firebase and Add subscribe button to category ad
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/res/layout/row_category_ad.xml
Labels: analytics, Categories Redesign + Ads in Categories

#2142 Account for 7.62.1 when migrating artwork settings
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
Labels: polish

#2141 Merge/release 7.62.1 into 7.63
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/res/layout/row_category_ad.xml
  version.properties
Labels: releases

#2144 Merge release-7.63-rc-2-into-main
  modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
  modules/features/discover/src/main/res/layout/row_category_ad.xml
  modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt
  version.properties
Labels: releases
